### ISSUE TITLE
Plugin creating guide or wiki?

### ISSUE THREAD

**Issue by kukrik** [qcubed/framework#1002]
@spekary, I think that I and others also want to create a plugin QCubed 3.0. You might want to write a guide or wiki to how we should do in order to be able to post new plugins to add QCubed 3.0 repository. Others can use Composer to pull down, etc...

But here is one of the hook that we need to test and try to either a new plugin is running as expected, etc...

Hence the questions:

1. Do we have to create your account for testing https://packagist.org/ access?
2. How do the plugins to transfer QCubed 3.0 repository?
3. How could in QCubed 3.0 repository renew rolling plugin fixes, etc?

Any thoughts?

**Comment by spekary** [comment]
The guide for creating the plugins is in the example code currently, but yes, I think I should start work on the Wiki soon to document all the additions.

your questions:

1. Plugin authors should create their own account on packagist.org. Just use mine as a model. 
2. A plugin author should check in the plugin to their own github repo, then post that as an issue. One of the core contributors would create a new repo in QCubed to add it to QCubed. They can even add the plugin author as a core contributor just for that plugin. The author should then set up the webhook to have packagist automatically update.
3. After it is set up, whenever you tag a release in the plugin, packagist automatically gets the new release and the next time someone does a composer update, they will get the new release.

**Comment by kukrik** [comment]
Thanks! I'll take to know. I close this topic.
