### ISSUE TITLE
Final 3.0 Push

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#1022]
We have a few outlying bugs to work through that are pertinent to the code itself.

We need another pass through the examples. I am working through the DataGrid examples for SimpleTable/DataGrid2.

There is still much to do though, before release. The big ones are:
1. Documentation. We have the examples site, which is a good tutorial. @vaibhav-kaushal , do you have any samples of what you can extract from the PHPDoc source code? Also, I think we need to really look at the Wiki doc. I have not looked at it much at all.
2. qcu.be website. This will take some work. It is currently a very old Drupal website. Can anyone work on it?
3. I am not particularly happy with the styles being used for the examples website. But that improvement could be a 3.0.1 release.

Longer term, I don't think StackOverflow is working as a bulletin board for Q & A. Perhaps there is a better Drupal bulletin board that is better at preventing spam?

**Comment by olegabr** [comment]
We have a scratch for the new website here: http://qcubed.github.io/ It is built on the technology of static site generator integrated into the github itself. It is a way to go IMO.

As for the SO, I'm not agree with you here. SO has become a very important part of the whole development infrastructure at a global scale. It is a common to estimate project value by a number of Q&A it has on a SO. There is a research to integrate SO into some IDEs to provide hints from SO directly in the IDE. We should be close to SO, I believe.
We need to integrate more with it. May be to show log of QAs from SO on the qcu.be web-site, along with a form to ask a new question may be. Another valuable enhancement would be to mirror all content from github issues created for SO questions back to SO and vice versa.

**Comment by spekary** [comment]
So we only host the examples site on qcu.be then? We will still need some kind of redirection from the index.html file on qcu.be to the github site.

Regarding SO, I have seen some questions that are perfectly fine for a forum get blasted by the other SO participants as not relavant to SO. We will need some kind of clarification from a How To Get Help page to post usage questions on SO, but post bug reports and feature requests on github.

**Comment by olegabr** [comment]
agree

**Comment by vaibhav-kaushal** [comment]
I have not ran the PhpDocumentor yet. I will, soon. 

You can read what I have written, so far at qcubed.in . I would love comments on that.

**Comment by vaibhav-kaushal** [comment]
Here is a *raw* attempt. Looks bad to me. Have to work on this thing.

**Comment by vaibhav-kaushal** [comment]
Here is a raw attempt. Looks bad to me. Have to work on this thing. http://v3-beta.api.qcubed.in

**Comment by vmakre** [comment]
I have wordpress ready system to change old qcu.be , but i don't have documentation , @vaibhav-kaushal  PhpDocumentor is very nice looking but it need some cleaning and polishing.  If you have some idea to finish new site before 3.0 final version , there will be a lot of job to do.  @spekary  bulletin board or forum  or blog? . Do we need old qcubed documentations or we'll go to only 3.0 ?

**Comment by vaibhav-kaushal** [comment]
@vmakre I think we can go to version 3.0 directly. The previous one is almost 3 years old now.

**Comment by matthiaz** [comment]
I just thought I'd share that stackoverflow recently added a documentation feature. 
http://stackoverflow.com/tour/documentation

This could be of use

**Comment by spekary** [comment]
A good thought. Looking into it, I am not sure how helpful it will be for us. It really is just a collection of examples. I don't call that documentation. I think it is really designed for something that has much broader use that QCubed. All of the topics listed there have their own documentation pages separate  from StackOverflow.

**Comment by vmakre** [comment]
Examples are the best part of documentation ,i solved every task and learned a lot with this. But we need some index and search option though . Maybe some type of blog or wiki like pages with tags will be helpful . So developing examples with static pages is bad idea as every page needs some meta tags or whatever for indexing via google search . Or maybe we can create new dynamic pages with search indexes (tags) and link them to static pages of examples. Just put text into database and make good autocomplete search input.

**Comment by vaibhav-kaushal** [comment]
@vmakre Yes, you are right. I think we can get work on that for 3.1 release. 

@spekary I think we are done with all the major issues. Only #1040 is remaining. For documentation (#1081), we have solved all the issues. We just need to re-run ApiGen and update the API Documentation. If you agree, we can release by weekend, easily!

All other types of documentation (guides, screencasts, tutorials, tips-n-tricks) should only start after the release.

**Comment by kukrik** [comment]
This issue https://github.com/qcubed/framework/issues/1032 should not be overlooked. Profiling Information is not working as expected, if the encoding is inside.

At the first opportunity I get to put only css correction... 

What do you think of this?

**Comment by olegabr** [comment]
@kukrik see the page now: http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/qcubed_query/qcache.php
Are you satisfied with it?

**Comment by kukrik** [comment]
This page does not touch to my style patches. I know this. Try again to refresh the browser.

<img width="1280" alt="screen shot 2016-10-04 at 21 09 09" src="https://cloud.githubusercontent.com/assets/2853034/19086704/d53e7992-8a77-11e6-8f47-4fddac1d2c7b.png">

Other pages work correctly. My goal is to make stylistically unified...

All of us are looking forward to it, that when we release Qcubed 3.0 :)

**Comment by olegabr** [comment]
There are no open issues remaining for the v3.0
We can do RC now.

**Comment by vaibhav-kaushal** [comment]
Yeah. We can :)

**Comment by spekary** [comment]
rc-3 is now a branch, as well as v3.1 for next release stuff.

Rc changes should only be doc related or major bugs. New stuff that is not involve major structural changes should go into v3.1. 

Version 4 with namespaceing that reflects the structure will involve the creation of new repositories for the separate parts. For example, v4 will have the breakout new ORM code that can be used separately from QCubed. 

Let's start checking in changes to rc-3 that talks about it being a real release. Readme file needs updating, version number, etc.

**Comment by kpirbhai** [comment]
Is there a way to switch composer to using rc-3? Or do we need to wait until it is on packagist?

**Comment by olegabr** [comment]
I've updated the app-starter to depend on the rc-3 branch. Packagist is updated too.

**Comment by vaibhav-kaushal** [comment]
I think we can do the release now. What do you guys say? @spekary Please comment.

**Comment by spekary** [comment]
Agreed. We need to clean up some things on the website and the doc. Also need to change the version number, but we are ready for a push on this.

**Comment by vaibhav-kaushal** [comment]
Can we do the release now?

**Comment by vaibhav-kaushal** [comment]
Since we have done the release, I think this can be closed.
