### ISSUE TITLE
Change QDataGrid2  -> QDataGrid, and QDataGrid->QDataGridLegacy?

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#1027]
While doing the examples code, it felt wrong to tell people to make a QDataGrid2. I think we shold change its name, but keep the old one as a "Leagcy" version. Is that fine with everyone?

**Comment by olegabr** [comment]
it's ok

**Comment by kukrik** [comment]
It's would also be nice! Lifelong learning from US 👍

**Comment by vaibhav-kaushal** [comment]
I had told the same thing some time back.

**Comment by spekary** [comment]
Fixed #1031

**Comment by aadityabagga** [comment]
I think some got left out..
https://github.com/qcubed/framework/pull/1036
