### ISSUE TITLE
Intentional solution or bug?

### ISSUE THREAD

**Issue by kukrik** [qcubed/framework#1035]
@spekary! I do not know either. After upgrading the latest version I tested examples. I discovered by accident that  4. Basic QForms - An introduction to QForms and QControls at server side event (QServerAction) does not work correctly if the configuration.php inside `define('__DESIGN_MODE__', 1);` is on. This throws the error:  `Fatal error: Call to a member function RenderScript() on null in /path/path/path/WEB/qcubed-shannon-beta/vendor/qcubed/framework/includes/base_controls/QFormBase.class.php on line 1820`.

If I turn off `define('__DESIGN_MODE__', 0);` then it works correctly.

Is it intentional? If yes, then you should comment on the examples to the server side event at __DESIGN_MODE__ turn off etc.

What are you thoughts?

**Comment by spekary** [comment]
Bug.

**Comment by olegabr** [comment]
@kukrik, please, check if the problem was solved

**Comment by kukrik** [comment]
This problem has been solved 👍! The topic may be closed!

EDIT: This time it was @spekary a fast man...
