### ISSUE TITLE
QDataGrid Paginator - New Page Number not being passsed

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/framework#1039]
I've updated to the latest commit and the Paginator links are not updating the data on screen to the offset so that the data is actually paging.

I cannot seem to figure out exactly where the problem is happening. The page number is being output to the link as "data-qap" correctly but is not being passed as the parameter to Page_Click in the QPaginatorBase.class.php file line 111. Null is being passed.

This was working before the removal of QDataGrid2. Everything else seems to be working perfectly.

**Comment by kpirbhai** [comment]
Found another instance of the parameter not being passed. The problem seems to be somewhere related to QAjaxControlAction. I have a control of my own that simply makes a clickable span within a DataGrid column. That new link click is also not having a parameter passed.

**Comment by kpirbhai** [comment]
Nevermind. My javascript file didn't update. Everything is working together perfectly now.

**Comment by spekary** [comment]
Can't reproduce this.
