### ISSUE TITLE
__FILE_CACHE__ and __IMAGE_CACHE__ should be optional

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#1040]
If these are not defined in the config file, or are defined as empty, we should ignore them. In other words, if I do not want to use file upload and image upload or creation tools, I shouldn't be forced to put writable directories in my doc root. @olegabr can you take a look at making these optional?

**Comment by spekary** [comment]
Also, could you document what these are for in the configuration.inc.sample file? 

I don't see where these defines are used in the framework, and I hate to put unnecessary defines in the configuration file. They are being required by the installation validator, but aren't actually used in the framework:

__APP_CACHE__
__APP_CACHE_ASSETS__
__APP_IMAGE_CACHE_ASSETS__
__APP_IMAGE_CACHE__
__APP_UPLOAD_ASSETS__
__APP_UPLOAD__

**Comment by vaibhav-kaushal** [comment]
@olegabr I cannot find the usage of these named variables. Git tells me you added them. It would be great to document them. It is worth 10-15 minutes of work and we would be 1 more step closer to the release of 3.0 😊

**Comment by vaibhav-kaushal** [comment]
In case no one is interested in working on this, I would proceed with deletion of these constants for now. We can reintroduce them in 3.1 in case they are needed.

**Comment by olegabr** [comment]
@vaibhav-kaushal I'll address it
