### ISSUE TITLE
Error after new install via composer

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#1045]
just got this:
```
 Error in PHP Script <docroot>/resources/vendor/qcubed/framework/assets/php/_devtools/start_page.php
Use of undefined constant __FILE_CACHE__ - assumed '__FILE_CACHE__'

Error Type: E_NOTICE

Source File: <docroot>/resources/vendor/qcubed/framework/includes/framework/QInstallationValidator.class.php Line: 178

Line 173:    			$obj->strMessage = "Images cache directory (" . __IMAGE_CACHE__ . ") needs to be writable";
Line 174:    			$obj->strCommandToFix = "chmod 777 " . __IMAGE_CACHE__;
Line 175:    			$result[] = $obj;
Line 176:    		}
Line 177:    
Line 178:    		if (!QFolder::isWritable(__FILE_CACHE__)) {
Line 179:    			$obj = new QInstallationValidationResult();
Line 180:    			$obj->strMessage = "Cache directory (" . __FILE_CACHE__ . ") needs to be writable";
Line 181:    			$obj->strCommandToFix = "chmod 777 " . __FILE_CACHE__;
Line 182:    			$result[] = $obj;
Line 183:    		}

Call Stack:

#0<docroot>/resources/vendor/qcubed/framework/includes/framework/QInstallationValidator.class.php(178): QcubedHandleError()
#1<docroot>/resources/vendor/qcubed/framework/assets/php/_devtools/start_page.php(6): QInstallationValidator::Validate()
```
commented this out, 

got also some more Errors / Notices, had to comment out some more,
see attachment:
[QInstallationValidator.class.php.txt](https://github.com/qcubed/framework/files/393380/QInstallationValidator.class.php.txt)

EDIT: think this belongs here:
https://github.com/qcubed/framework/issues/1040

**Comment by kukrik** [comment]
Yes, @olegabr and @spekary discuss further... @olegabr merged their commits, but @spekary did not agree ...

Temporarily must manually change a bit: https://github.com/qcubed/framework/blob/beta-3.0/install/project/includes/configuration/configuration.inc.sample.php

**Comment by nlomb** [comment]
thanks, changed this in my configuration.inc.php, was using an old style one ...
( new style looks more "cleaned up" )

**Comment by olegabr** [comment]
@nlomb, seems that your configuration.inc.php file needs to be updated with recent changes.

**Comment by nlomb** [comment]
@olegabr 
closing this
