### ISSUE TITLE
problem with mysql Distrib 5.7.(xx) and QCubed Release (QCubed 2.2)

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#1054]
maybe off topic ...

got the following error message after server / mysql - update
```
MySqli Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'idaflexwf.t0.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Exception Type: QMySqliDatabaseException

Exception Report Generated: Monday, August 8 2016, 3:20:56 AM
PHP Version: 7.0.8-0ubuntu0.16.04.2; Zend Engine Version: 3.0.0; QCubed Version: 2.2 Development Release (QCubed 2.2)
Application: Apache/2.4.18 (Ubuntu); Server Name: server-02
HTTP User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0 `
```
had to edit "QMySqliDatabase.class.php"
```php
		public function Connect() {
			// Connect to the Database Server
			$this->objMySqli = new mysqli($this->Server, $this->Username, $this->Password, $this->Database, $this->Port);

			if (!$this->objMySqli)
				throw new QMySqliDatabaseException("Unable to connect to Database", -1, null);
			
			if ($this->objMySqli->error)
				throw new QMySqliDatabaseException($this->objMySqli->error, $this->objMySqli->errno, null);

			// Update "Connected" Flag
			$this->blnConnectedFlag = true;

			// Set to AutoCommit
			$this->NonQuery('SET AUTOCOMMIT=1;');

			// set SESSION sqlmode for backward compatibility
			$this->NonQuery('SET SESSION sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"');

			// Set NAMES (if applicable)
			if (array_key_exists('encoding', $this->objConfigArray))
				$this->NonQuery('SET NAMES ' . $this->objConfigArray['encoding'] . ';');
		}
```

**Comment by olegabr** [comment]
"set SESSION sqlmode for backward compatibility"

it is better to do it in mysql config file on the server side.

**Comment by spekary** [comment]
"MySQL 5.7.5 and up implements detection of functional dependence." from the Mysql doc for group by handing.

The way to fix this is to detect the version of MySQL, and possibly even detect the ONLY_FULL_GROUP_BY setting in MySQL, and then turn on:

```	protected $blnOnlyFullGroupBy = true;```

in the database adapter. Perhaps instead of doing this detection every time PHP starts up, the detection could be done in the install script and then we provide a way to manually configure the adapter through a configuration file.

**Comment by spekary** [comment]
For now, try editing your database adapter to turn on ```$blnOnlyFullGroupBy``` and see if that fixes the problem.

**Comment by nlomb** [comment]
not sure if it occurs in QCubed 3.0 also, will test

made this for backward compatibility,did not want to deactivate a sql standard feature for all databases but only for (old) QCubed 2.2 apps,
therefore put it in SESSION sqlmode (works for me)

**Comment by spekary** [comment]
Anyone using Mysql v 5.7.5 will run into this problem unless we fix the database adapter. $blnOnlyFullGroupBy  is in v2.2 also, so you can test if this works there.

**Comment by nlomb** [comment]
just tested editing my QCubed 2.2 QDatabaseBase.class.php line 52
```
protected $blnOnlyFullGroupBy = true; // should be set in sub-classes as appropriate
```
got:
```
MySqli Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM
    `document` AS `t0`
    
WHERE
    (
    `t0`.`id` IS NOT NULL
   ' at line 3

Exception Type: QMySqliDatabaseException

Source File: /<document-root>/qcubed/includes/qcubed/_core/framework/QDatabaseBase.class.php Line: 150

Line 145:    			if ($this->blnEnableProfiling) {
Line 146:    				$timerName = 'queryExec' . mt_rand() ;
Line 147:    				QTimer::Start($timerName);
Line 148:    			}
Line 149:    			
Line 150:    			$result = $this->ExecuteQuery($strQuery);
Line 151:    			
Line 152:    			if ($this->blnEnableProfiling) {
Line 153:    				$dblQueryTime = QTimer::Stop($timerName);
Line 154:    				QTimer::Reset($timerName);
Line 155:    				

Database Error Number:  1064

Query:   Show/Hide

Call Stack:

#0 <document-root>/qcubed/includes/qcubed/_core/framework/QDatabaseBase.class.php(150): QMySqli5Database->ExecuteQuery('SELECT DISTINCT...')
```
seems a little more complex,did not expect sql syntax error here ...
will for now keep my workaround ... (was ok with previous mysql version)

**Comment by vaibhav-kaushal** [comment]
Does the problem exist for QCubed 3.0 as well?

**Comment by nlomb** [comment]
seems QCubed 3.0 is clean, just checked example:

\<DOCUMENTROOT>/vendor/qcubed/framework/assets/php/examples/qcubed_query/qqclause.php

there is "GROUP BY in action"

**Comment by kukrik** [comment]
@spekary, perhaps offtopic question, but I want to clarify in configuratsion.inc.sample.php
one row (line 285).

Which is the more correct: `onlyfullgroupby '=> Defined by db adapter)));` or `'onlyfullgroupby' => 'Defined by db adapter')));` ???

I put this in the development of their apostrophes.

How is it?

**Comment by spekary** [comment]
Not quite sure what you are asking, but I think you want:

'onlyfullgroupby'=>true

And then have the adapter detect that if it is set like this, then use it as an override. If this is missing from the options, then do the default.

**Comment by kukrik** [comment]
I thought it, just in case, I asked over. Thank you! The topic may be again closed.
