### ISSUE TITLE
ApiGen for Documentation? 

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#1062]
Has anyone used ApiGen so far? (http://www.apigen.org)?

It seems to be a good library for documentation.

Views?

**Comment by vmakre** [comment]
Yes i tested apigen and is ok we can use it for documentation . Another point is class view and left menu organization   , here we need namespace organization  @spekary  can you help there?  to be like http://www.doctrine-project.org/api/orm/2.4/index.html  , on left menu Namespaces, Classes , etc...

**Comment by vaibhav-kaushal** [comment]
I think we can start with **some** namespacing in 3.1. I would like to start with QForm. :)

**Comment by spekary** [comment]
Great, but lets start with a plan. Perhaps propose a namespace structure for UI over in #1063.

**Comment by vaibhav-kaushal** [comment]
Closing this in favor of #1081 . Also, I have listed #1063 in a new roadmap discussion in #1082
