### ISSUE TITLE
qcubed plugins location 

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#1065]
This is my idea to move folder "project\includes\plugins"  to
"vendor\qcubed\plugins" and to call plugin classes via namespaces like  \Plugins\plugin_bootstrap\someclass .
With this we can divide plugin code  from plugin dependency from another plugins and
plugin will stay in vendor so we can install deinstall or update via composer.
With this we can know that plugin is for qcubed (folder is inside qcubed)  ,and we can see in vendor dependency installed plugins. I think  this will make some logically distinction as old plugin installer doesn't work and we are going to composer. Also we will remove same plugin naming problems  , "vendor\bootstrap"   will be different from "vendor\qcubed\plugins\bootstrap".
This is first step for code organization as in next steps we can divide plugin assets in separate folders and copy them to project assets .Also project assets can have vendor/qcubed/plugins/...  analogue to plugin folder.
https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md
What do you think about?

**Comment by spekary** [comment]
I think what your asking for is already done in beta 3.

- \vendor\qcubed\plugins: Code that is updated during a composer Update. User does not edit this code.
- \project\includes\plugins: Code that is copied one time from each plugins "install" directory. See QCKEditor and QDataTables for examples. These are stubs that allow the user to edit the override files, and not have these edits be erased during composer udpate. This is the same scaffolding  architecture that is all throughout qcubed, such as /vendor/qcubed/framework/includes/base_controls, and /project/includes/controls. 

Namespace is already there too. And, custom installer work is already done to make this work.

**Comment by vmakre** [comment]
Yes vendor was root folder before but now is ok.
Thanks  @spekary  ,   we can close this issue.
