### ISSUE TITLE
found two minor issues

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#1072]
QInstallationValidator.class.php creates this:
```
Welcome to QCubed!
PHP5 Model-View-Controller framework

This simple wizard will help you configure QCubed for first use. It'll take you just a couple minutes. If you have any questions along the way, feel free to ping us on the support forums, a vibrant community is there to help you all the time. There's also a chat room where you can get help right away.

Here's what you need to do:

    Cache directory (/usr/data/share/www/tegralink/resources/project/tmp/cache/purifier) needs to be writable

Here are commands that can fix several of these issues:

chmod 777 <MY-DOCROOT>/resources/project/tmp/cache/purifier
```
errors: 

1. - should be "PHP5 - PHP7 Model-View-Controller framework"
2. - "ezyang/htmlpurifier" is not installed

**Comment by vaibhav-kaushal** [comment]
@nlomb I think we should install HTMLPurifier when QCubed installs! We are offering the functionality to our users anyway.

**Comment by nlomb** [comment]
@vaibhav-kaushal 
Not sure about this, HTMLPurifier is really BIG and might decrease performance; has anyone compared performance with and without it?
Ii think in a closed secure (intranet, https, vpn ore ssh-tunnel) environment it is not needed, but "in the wild" CSS - protection is really necessary, so installing it should be the choice of the developer / user depending on use case.

On the other side if the performance impact is tolerable it should be installed anyhow.

**Comment by nlomb** [comment]
BTW: is it possible to move / join this issue to https://github.com/qcubed/framework/pull/1080

**Comment by olegabr** [comment]
@nlomb this issue now stay for the html purifier part only. We should not require it if it is not installed. it should not be hard to check it by e.g. some file existence.

**Comment by vaibhav-kaushal** [comment]
@olegabr Then we should move this into 3.1 or just close this. We can reopen or create a new one when we need to discuss this again! Too many open issues which have been removed for now should be closed, IMHO.
