### ISSUE TITLE
configuration.inc.php being overwritten by composer

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/framework#1074]
For the last couple of days, running composer update is suddenly overwriting my configuration.inc.php file. Is this supposed to happen?

**Comment by spekary** [comment]
Definitely not. But I don't see how that could happen, it must be something else. There is no configuration.inc.php file in the qcubed repo. The only thing that creates that is the installer wizard, but you have to run the installer wizard yourself, composer does not run it. The other possibility is something you are doing in git.

**Comment by kpirbhai** [comment]
I found the following lines starting at line 116 in the file vendor/qcubed/composer/Installer.php

```
		// fix up the configuration file
		$strFile = file_get_contents($strConfigDirectory . '/configuration.inc.sample.php');
		if ($strFile) {
			$strFile = str_replace (['{docroot}', '{vd}', '{subdir}'], [$strDocRoot, '', $strSubDirectory], $strFile);
			file_put_contents($strConfigDirectory . '/configuration.inc.php', $strFile);
		}
```

It seems like that is what is causing the config file to be overwritten.

**Comment by spekary** [comment]
That whole section of code is in the "install" function, which is only supposed to be called by the "composer install" command. If composer is calling it when you execute "composer update", then something is seriously wrong. In a previous post, you mentioned something about the "vendor" directory missing. Are you moving the vendor directory, or renaming it, and then calling "composer update"? If so, I can imagine that composer gets confused and does an install instead. Please describe your process more in depth so we can understand what is going on. 

You can fix that code you pointed to detect the existance of the file first so it doesn't get overwritten.

**Comment by kpirbhai** [comment]
I'm leaving the vendor folder out of git. The whole folder is ignored. I just started that last night. Before the whole vendor folder was being tracked. I'm fairly new to using composer, but from all that I'm reading, that seems to be the thing to do. 

So, when I change branches, I have to rerun composer update to have the vendor folder created.

**Comment by spekary** [comment]
I think I see now. You shouldn't have to do that. Try the following setup:
- /docroot
   - .gitignore
   - /project
   - /vendor
   - (and other files)

In your .gitignore file, put '/vendor/'. 

When you want to do app-level git stuff, change directory to /docroot and the vendor direcotry will be ignored. If you want to update qcubed, change directory to /vendor/qcubed/framework and do a git pull there. Or, you can be in /docroot and do a 'composer update' and that should get the latest too. You should not need to delete the vendor directory to update it. And this setup will prevent the vendor directory from being checked in, but will check in the composer.lock file so you can recreate the vendor directory if needed.

**Comment by kpirbhai** [comment]
Your proposed idea what pretty much what I was doing but that only solves the problem on the computer I work on everyday...and even that only sort of. I created a script to run pre-update and post-update which has solved both this problem and the QControl extending from Bootstrap problem.

I put my script below in case someone else comes across this problem. Hope it saves someone some time. Thank you!

```
namespace AAComposerScripts;

/**
 * Composer script to help with some weird stuff
 * - QControl extending from the bootstrap control when the vendor folder has to be created from scratch causes a problem
 *      So....copy mine with bootstrap to a bakup. Have an original to copy over mine.
 *      Restore mine from the bakup after the update.
 * - configuration.inc.php is being overwritten when no vendor folder.
 *      So...copy mine to backup then restore after update.
 */
class ComposerScript {
    static $QControlOriginal;
    static $QControlMine;
    static $QControlBak;
    static $QConfigMine;
    static $QConfigBak;
    
    static public function preUpdate() {
        // get the project/includes/controls/QControl.class.php file
        static::$QControlMine = dirname(__FILE__) . '/../project/includes/controls/QControl.class.php';
        static::$QControlBak = dirname(__FILE__) . '/../project/includes/controls/QControl.class.php.bak';
        static::$QControlOriginal = dirname(__FILE__) . '/../project/includes/controls/QControl.class.php.org';
        static::$QConfigMine = dirname(__FILE__) . '/../project/includes/configuration/configuration.inc.php';
        static::$QConfigBak  = dirname(__FILE__) . '/../project/includes/configuration/configuration.inc.php.bak';
        
        // copy my good file to the bakup file
        copy(static::$QControlMine, static::$QControlBak);

        // copy original file to "mine"
        copy(static::$QControlOriginal, static::$QControlMine);
        
        // copy my config file to bakup file
        copy(static::$QConfigMine, static::$QConfigBak);
    }
    
    static public function postUpdate() {
        // copy bak file to mine
        copy(static::$QControlBak, static::$QControlMine);
        copy(static::$QConfigBak, static::$QConfigMine);
        
        // get rid of bak files
        unlink(static::$QControlBak);
        unlink(static::$QConfigBak);
    }
}
```

**Comment by kukrik** [comment]
I would ask to open this topic. Our problem is not the first time we want to use Bootstrap. In development phase is always uncomfortable Composer upgrade if necessary. 

@kpirbhai script seems to be good, I have not tried it. Can you could write more to where you need to put  your script? I see it in your script, but where exactly...

@spekary, your qcubed/plugin_bootstrap is super good. What do you think, as you describe it, how to upgrade Composer unproblematic. In this case, than we had previously added this line to your recommendation `abstract class QControl extends QCubed\Plugin\Bootstrap\Control {`, how to upgrade Composer, etc ... Then how to use @kpirbhai script or whatever?

Thoughts?

**Comment by kpirbhai** [comment]
I added a couple of things to the composer.json script which will run my script that has already been included here.  My script ( the one included above ) lives at the root in a folder called "scripts". That folder is on the same level as "project" and "vendor".

Here's the two sections I added to the composer.json file:

```
  "autoload": {
      "psr-0": {
          "project": ""
      },
      "psr-4": {
          "AAComposerScripts\\": "scripts/"
      }
  },
```
and
```
  "scripts": {
      "pre-update-cmd":"AAComposerScripts\\ComposerScript::preUpdate",
      "post-update-cmd":"AAComposerScripts\\ComposerScript::postUpdate"
  }
```
That's all you have to do. Has worked every time both on my laptop running wamp and on the remote server running apache and ngix.
