### ISSUE TITLE
Documentation for version 3.0

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#1081]
I think the main features are in now and we can move to release state at anytime. This time, we should have some good documentation. I will do what I can, but API documentation is a must. It is best to make a list of what we want to do with the Documentation. Here are the concerns: 

- [x] Which documentation system to use? PhpDocumentor or ApiGen (Speaking of which, the discussion of #1062 should be moved here)
- [x] Should we have screencasts? A YouTube channel to begin with?
- [x] Why can't we make a repo for QCubed documentation right into the **qcubed.github.io** repo? We can make an index page, and do the documentation for every version and move forward with that! It would be easy enough! Think of - `http://qcubed.github.io/doc/v3/index.html`. All we will need is the generated HTML and we will be able to port it anywhere we need. Anyone will be able to change the API doc, regenerate and update (pull requests, of course).

I hope we will have some good documentation this time?

**Comment by vaibhav-kaushal** [comment]
About the documentation: Have a look at http://qcubed.github.io/ I have updated the link to Documentation (http://qcubed.github.io/doc/3.0/index.html)

It's not Exceptionally well, but there it is :)

**Comment by spekary** [comment]
I think it is a good first step. How do we control the organization. I see we can create a package name. Are there sub-packages and if so, how to define those? Any other organizing tools?

**Comment by vaibhav-kaushal** [comment]
I believe, the documentation can be stabilized only after the release is done. At least for this version, that would be a better idea. It will give us all a 'release' which has been pending since long and anyone who wants to document will know that whatever they are trying to document is not going to change overnight. Once the release is out, we can go on working on the documentation and the next release will be a hell lot better. 

However, I think that for this release, we can go for Package naming at the very least.

I would suggest that we can go with these names:

  - Framework
  - Codegen
  - Controls
  - Base Controls
  - Forms Library

...and so on.

**Comment by vaibhav-kaushal** [comment]
ApiGen is better than PhpDocumentor. We should be using that. However, for the sake of API documentation, we should exclude the examples directory. Will look into that. 

Have created a channel: https://www.youtube.com/channel/UCnWSEzp6CjKyD9eRh0iNYOg

Will have to link content there. If you guys do have some screencasts, please upload on YouTube. I will create a playlist and put them there!

**Comment by olegabr** [comment]
The examples for v3.0 are live here: http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/index.php

**Comment by vaibhav-kaushal** [comment]
It's working. Thanks :) 

@olegabr This is MySQL DB, right?

**Comment by olegabr** [comment]
yes, it is mysql

**Comment by vaibhav-kaushal** [comment]
Can you look at: #1101 ? I have made a comment there. I am not sure if it makes a difference.

**Comment by olegabr** [comment]
API docs are ready. Closing it.
