### ISSUE TITLE
Use OpenSSL methods in QCryptography

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#1088]
PHP 7.1 (soon to be released) is going to deprecate (and soon remove) the support for mcrypt. Links: 

  - https://dotdev.co/upcoming-changes-in-php-7-1-76ebea53b820#.i4kcif1lx
  - https://github.com/php/php-src/pull/1996
  - https://wiki.php.net/rfc/mcrypt-viking-funeral

OpenSSL Library is the recommended way to go. 

At present, we are using mcrypt in QCryptography class/file. I believe we should replace that with openssl_* functions.

**Comment by spekary** [comment]
OK. I think this needs to be in an update to 3.0 since that website points out that mcrypt hasn't been updated since 2007 and is basically obsolete.

**Comment by vaibhav-kaushal** [comment]
From what I have been reading in this context, there is this library: https://github.com/jedisct1/libsodium which seems to be gaining momentum slowly, steadily. I have not gone through it much so can't say much but looks promising from what I have read. The pain is - you have to **compile** it. Not all developers are happy with that. Even if you are an experienced developer, to compile it everywhere is an un-necessary pain. 

At the same time it looks like openssl is built into PHP 5.3+ (from what I see on Mac (native+homebrew) and Ubuntu) - which mean no need to compile or install anything! I think we need to confirm if openssl is already built-in and if it is, then we can move ahead with that. 

Also, this time, let's make AES-256 the default encryption, if possible. While Triple-DES is no issue either, AES is stronger and **recommended** (by US Government, and that makes it quite famous; the aim being - the defaults are set to something which is widely accepted (Intel has hardware instructions for AES and no other Cipher) and recommended).

**Comment by aadityabagga** [comment]
Maybe this can be used:
https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

**Comment by vaibhav-kaushal** [comment]
From what I have seen so far, openssl extension seems to be enabled by default in PHP with every distribution above 5.3.

Since no one has put in any comments since some time here, I am moving ahead with implementation of QCryptography using openssl functions available in PHP.

**Comment by spekary** [comment]
Yes, please.

**Comment by vaibhav-kaushal** [comment]
Please check the PR. 
#1092 
Closing this in favor of the PR.
