### ISSUE TITLE
__PURIFIER__CACHE__ directory not present

### ISSUE THREAD

**Issue by aadityabagga** [qcubed/framework#1091]
```__PURIFIER__CACHE__``` directory is defined [here](https://github.com/qcubed/framework/blob/beta-3.0/install/project/includes/configuration/configuration.inc.sample.php#L453) and is checked in the [installer](https://github.com/qcubed/framework/blob/1b6d67926ee16a182e554f583b20cf86b2a89a65/includes/framework/QInstallationValidator.class.php#L185) also, but is missing from the [required location](https://github.com/qcubed/framework/tree/beta-3.0/install/project/tmp/cache).

P.S. I tried creating the folder and adding it to git, but as unable to do so as it was being ignored by .gitignore.

**Comment by vaibhav-kaushal** [comment]
You can create a directory locally for that and copy that .gitignore file in the directory that you created. Let me know if it worked.

**Comment by spekary** [comment]
We really should make this optional and not require it to be defined. If it is defined, the installer wizard can check to see if it exists, and tell you to create it if it does not exist.

**Comment by vaibhav-kaushal** [comment]
@spekary I agree with you.

**Comment by vaibhav-kaushal** [comment]
We can put it back with better support, documentation, examples, and conviction in 3.1

@aadityabagga Please submit a pull request.
