### ISSUE TITLE
Database Profiling Tool does not work as expected with 'encoding' => 'utf8'

### ISSUE THREAD

**Issue by kukrik** [qcubed/framework#1101]
Two issue are together, it put forth to confuse all. I will put another issue here... 

Background Information for hint: https://github.com/qcubed/framework/pull/1099.

I found here the configuration.inc.php inside the line of `'encoding' => 'utf8'` dislike to Profiling Information. It throws the error: MySqli Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET NAMES utf8' at line 1.

If this line (`//'encoding' => 'utf8'`) to hide it Profiling Information is working properly. But this line is very necessary to save and display the accented characters correctly.

I have to realize that this is a simple mistake.

But I was looking for a solution, have not found the right solution ...

Before you want to ask how you are running Profiling Information. Linux platform on top, or whatever?

I would like to provide improvements in CSS before QCubed 3.0.0.

EDIT: I have a MySQL version 5.7.10.

@kpirbhai question: @kukrik, Are you referring to if the profiling output is within the main "Form" block that it doesn't work much of the time? If so, I've been having the problem as well. I've looked at it some but haven't had enough time to really dig in. I put RenderBegin and RenderEnd in the include header and footer respectively right after and before the body tags. I've gotten errors that $j and or jQuery aren't defined when clicking on the profiling output link.

My answer: @kpirbhai, maybe I understand your question correctly. This is another issue that I wanted to talk about.

Database Profiling Tool does not work as expected when in configuration.inc.php is` 'encoding' => 'utf8'` enabled. It throws the error: MySqli Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET NAMES utf8' at line 1.

When `'encoding' => 'utf8'` is not active, it Database Profiling Tool works as expected.

I think the problem lies elsewhere, not what you thought?!

From here it is necessary to find a solution to this issue...

**Comment by vaibhav-kaushal** [comment]
@kukrik Are you getting any error with PHP? Do you see something unusual in MySQL logs? 

I do not use MySQL myself, however, I found this: http://php.net/manual/en/mysqli.set-charset.php 

There is a note at the bottom of that page which says: 

```
Note:
This is the preferred way to change the charset. Using mysqli_query() to set it (such as SET NAMES utf8) is not recommended. See the MySQL character set concepts section for more information.
```

I also found this: https://github.com/qcubed/framework/blob/beta-3.0/includes/database/QMySqliDatabase.class.php#L89

We are doing exactly what we are not supposed to! I do not have a MySQL installation ready with me. Can @spekary or @scottux help?

**Comment by olegabr** [comment]
@vaibhav-kaushal this code is really aged: `basilieus authored on 24 Apr 2009`

**Comment by vaibhav-kaushal** [comment]
Alright. Can we fix this? By using MySQLi's set_charset?

**Comment by kukrik** [comment]
Yes, the exchange of encoding to set_charset is probably the right solution.

I had previously explore but did not do farther... I did tests, very good results. Umlauts are correct and Database Profiling Tool works as expected: https://github.com/qcubed/framework/pull/1099/commits/fee004714632b833a16f9eea6841681baba2fe10

So be both patch to merge https://github.com/qcubed/framework/pull/1099. Both issues can be closed after the merger.

@vaibhav-kaushal, thanks for the encouragement!

**Comment by vaibhav-kaushal** [comment]
@kukrik The changes are only in the name of the array. I am not sure how the thing started working again by just changing the key name in the array. I have added my review comments. Can you please try changing the line here ( https://github.com/qcubed/framework/pull/1099/files#diff-e6096ba470c31dc7113e151281541b49R89 ) ? This is the recommended method said on the PHP site.

**Comment by kukrik** [comment]
I know that my tests were quick and dirty at night... I do not see here in your comments. I have one thought, but I have to delve a little bit. I will let know...

**Comment by olegabr** [comment]
I've moved it to 3.1 because this issue is unclear and there is no way to reproduce it. No reason to delay a release for it.

**Comment by kukrik** [comment]
Can I close this ticket?
