### ISSUE TITLE
Problems with DbBackedSessionHandler when using new QCryptography

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#1103]
When I use DbBackedSessionHandler, it gives me the error: `gzuncompress(): data error`

Is was not happening when we were using the text field. Also, it is occasional, hence I do not know when and why it happens.

*EDIT*: I ran some tests around this and the recent changes. I will post them as comment below.

**Comment by vaibhav-kaushal** [comment]
@spekary When I use `QDbBackedSessionHandler` along with your recent changes to `QCryptography` in their default settings (Blob column implementation in the DB for Session Handling and *Encryption* and *Compression* enabled in the QDbBackedSessionHandler class file), everything gets buggy like hell! Here are the things that I have observed: 

- With default settings, sometimes `gzuncompress` fails (and this happens randomly, without any set pattern)
![screen shot 2016-09-18 at 1 21 34 am](https://cloud.githubusercontent.com/assets/2824682/18610626/7b5d2752-7d3e-11e6-816a-8f99684b2de4.png)
- If I disable compression in the DbBackedSessionHandler, sometimes I get the error from PHP saying that it could not decode session object. This happens for sure when I destroy a user's session but not necessarily. While the user is logged in, or logged out, it still happens on pages. So this too, is random. 
![screen shot 2016-09-18 at 1 25 29 am](https://cloud.githubusercontent.com/assets/2824682/18610644/0e942750-7d3f-11e6-99aa-3595486e2c75.png)
- If I enable compression and disable encryption in the DbBackedSessionHandler, I get error from PostgreSQL saying `invalid byte sequence for encoding "UTF8"`
![screen shot 2016-09-18 at 1 32 47 am](https://cloud.githubusercontent.com/assets/2824682/18610682/03d68f50-7d40-11e6-90f6-1ce934293311.png)
- If I disable both encryption and compression, world comes back to order.
- If I roll back the changes you have done to QCryptography and instead use the one where we have default IV and key defined in the config file, no errors prop-up either.

So all I can conclude after almost 8 hours of chasing the culprit - the new changes to QCryptography, where you use HMAC for integrity checks. 

I think we should use the IV and Key version with the defaults in the config file. It is not possible to test this version well enough without going too deep into compression and encryption, or at least one of them. We started with changes to QCryptography to avoid any problems *mcrypt* would be causing and I think we had achieved that with the version where we ask the user to set the IV and key in the config file.

I understand your concerns about the data tampering part but can we get that done by using another variable on QCryptography or do it in 3.1? It is too buggy right now!

**Comment by spekary** [comment]
Yep. I have a fix. Testing now and will present it soon. The problems is using a static IV is just wrong and completely defeats the purpose of the IV. Yes, we could document that, but we really should do it correctly. Encryption is tricky.

**Comment by spekary** [comment]
See #1104

**Comment by vaibhav-kaushal** [comment]
I will need a little time to review this one. Please bear with me.

**Comment by aadityabagga** [comment]
Even after merging these changes, issues are there.

* 1 (new constants not defined):
~~~~
define('__FORM_STATE_HANDLER__', 'QDbBackedFormStateHandler');


//			define('__DB_BACKED_FORM_STATE_HANDLER_ENCRYPTION_KEY__', 'a243$5@13');
//			define('__DB_BACKED_FORM_STATE_HANDLER_HASH_KEY__', '0293()aih');
~~~~
http://imgur.com/FBCrpn8
~~~~
 Error in PHP Script /index.php
pg_query(): Query failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xda 0xed

Error Type: E_WARNING
~~~~

* 2 (new constants defined):
~~~~
define('__FORM_STATE_HANDLER__', 'QDbBackedFormStateHandler');


			define('__DB_BACKED_FORM_STATE_HANDLER_ENCRYPTION_KEY__', 'a243$5@13');
			define('__DB_BACKED_FORM_STATE_HANDLER_HASH_KEY__', '0293()aih');
~~~~
Works, but sometimes gives following error message:
http://imgur.com/3bL0M9W
~~~~
pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint "qc_session_pkey"
DETAIL:  Key (id)=(PHPSESSID.r5sou96k463li2vqb7uufftf33) already exists.

Error Type: E_WARNING

Rendered Page: Click here to view contents able to be rendered.

Source File: /www/h3.example.com/vendor/qcubed/framework/includes/database/QPostgreSqlDatabase.class.php Line: 255

Line 250:    			return $objPgSqlDatabaseResult;
Line 251:    		}
Line 252:    
Line 253:    		protected function ExecuteNonQuery($strNonQuery) {
Line 254:    			// Perform the Query
Line 255:    			$objResult = pg_query($this->objPgSql, $strNonQuery);
Line 256:    			if (!$objResult)
Line 257:    				throw new QPostgreSqlDatabaseException(pg_last_error(), 0, $strNonQuery);
Line 258:    			$this->objMostRecentResult = $objResult;
Line 259:    		}
Line 260:    
~~~~

* 3:
Always get following error when trying to login to our application
~~~~
 Error in PHP Script /index.php/learn
gzuncompress(): data error

Error Type: E_WARNING

Source File: /www/h3.example.com/vendor/qcubed/framework/includes/framework/QDbBackedSessionHandler.class.php Line: 160

Line 155:    				catch(Exception $e) {
Line 156:    				}
Line 157:    			}
Line 158:    
Line 159:    			if (self::$blnCompress) {
Line 160:    				$strData = gzuncompress($strData);
Line 161:    			}
Line 162:    
Line 163:    			
Line 164:    			return $strData;
Line 165:    		}
~~~~
http://imgur.com/a/WtXnB

**Comment by kukrik** [comment]
Try to make an appointment https://github.com/qcubed/framework/blob/beta-3.0/install/project/includes/configuration/configuration.inc.sample.php#L283, perhaps put the slashes to `// 'encoding' => 'utf8'.`

Look, if something happens?

I deal with a similar problem, and I shall still...

**Comment by vaibhav-kaushal** [comment]
@kukrik He ( @aadityabagga ) is using Postgresql.

**Comment by kukrik** [comment]
I also got to understand :). I saw this label: 
```
Error in PHP Script /index.php
pg_query(): Query failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xda 0xed

Error Type: E_WARNING
```

**Comment by kukrik** [comment]
May I ask in what Postgresql is better :)? I thought I could try it in the meantime, but the lack of time have not tried...

**Comment by spekary** [comment]
Not seeing errors in MySQL, so perhaps a config problem. Try the following:

Use a TEXT field for the session and form data, but make sure blnBase64 is true. This should be the default. If you are seeing utf-8 errors, then likely blnBase64 is turned off. Since blnBase64 is back on by default now, either you did not update and you think you did, or you are somewhere explicitly setting this to false. Also, be sure to clear out the old session and formstate data from the database before trying to use it.

The other config that should work is using a Byte field, with blnBase64 explicilty set to false (do this near the top of your prepend file). Again, make sure you clear out your old session and formstate data before trying this.

**Comment by spekary** [comment]
So, I just found this comment under session_save_handler in the PHP docs:

> As of PHP 5.0.5 the write and close handlers are called after object destruction and therefore cannot use objects or throw exceptions. Exceptions are not able to be caught since will not be caught nor will any exception trace be displayed and the execution will just cease unexpectedly. The object destructors can however use sessions.

This may be some of the problems I am seeing with random script failure. To accomplish this, we would need to remove a number of references to objects in the write handler for QDbBackedSessionHandler. I am not sure why it appears to work most of the time, and the problems I am having may be just in the garbage collector, but we can't use a database object here apparently. We will have not make direct sql calls into the database. I am not sure if I am reading this right though.

**Comment by vaibhav-kaushal** [comment]
@spekary While you have noble intentions with your suggestions with PostgreSQL, we cannot ask everyone to do that. Not everyone is going to read the docs carefully either. So the defaults have to work. I am still overloaded. It's 12:47 AM here. Will test it tomorrow and see if the new commit you have made passes.

Also, @kukrik has a problem. I have added review comments on #1099 but do not have a MySQL installation to try these on. It will take some time for me to setup. Since you use MySQL, if possible, see if my suggested changes work. 

Also, I received a message on Quora. Someone asked why http://qcu.be was down. 😕 Is it possible to bring it up? Can we redirect it some other place?

**Comment by vaibhav-kaushal** [comment]
@kukrik PostgreSQL is technically superior in many ways than MySQL, expect handling massive volumes of writes (like more than 50 updates per second on single object)! 

Some features include: 

- Very good JSON handling (one of my favorite features).
- Very integrated structure from parsing to storage
- Well developed Full-Text-Search
- Better SQL compliance
- More failure-resistant than MySQL.
- Transactional to the core

There are a lot of other things where PostgreSQL excels. You can google it. You will come to know :)

**Comment by kukrik** [comment]
@vaibhav-kaushal, thank you a quick overview! I should sometime peruse it. This will require more time, focus and commitment. 
At the moment, unfortunately, I do not have much free time because I have another working :(

**Comment by spekary** [comment]
> While you have noble intentions with your suggestions with PostgreSQL, we cannot ask everyone to do that. 

Perhaps you misunderstood me. This merge request basically changes QDbBackedSessionStateHandler back to the original defaults, with blnBase64 being true and being able to use a TEXT field, regardless of PG and MYSQL. However, it leaves in the new code that is the special case for PG using a byte field, but that will only be turned on when it detects PG and a byte field.

The new functionality is to be able to use a binary BLOB field in a different database (like MySQL) and also turn off blnBase64 so that it saves space.

However, per my other point, this all may be moot. The comment I found in the PHP documentation suggests that we need to remove all references to objects in the write and close functions, which definitely complicates things, and makes it impossible to use the QCubed database adapters to provide some abstraction without significant work. I am not sure I believe the comment, because if true, it should just not work. What I am seeing is behavior indicating it is working most of the time, but I get occassional server drops which I think are related to this problem.

**Comment by kukrik** [comment]
I have a question regarding the fact that the site http://qcu.be is down. I quickly put it on your server and can be found http://qcubed.ead.ee. This may be a temporary solution for you.

I do not know whether my plan is good?

I ask the server administrator to whether they can sponsor for community website.

They were some of the projects supported in the past and so on.

Or I throw this silly idea out of your head?

**Comment by spekary** [comment]
I did a redirect to qcubed.github.io.  We can all now hack away at the home page, since everything will be right here in github. The only thing that will be on the qcu.be server is the examples that we can direct people to. Any volunteers to make an awesome home page?

**Comment by kukrik** [comment]
This site http://qcubed.github.io is the most better and more appropriate thought!

**Comment by aadityabagga** [comment]
I changed the data type for the ```data``` field in ```qc_session``` from ```bytea``` to ```text```  as suggested by @spekary in https://github.com/qcubed/framework/issues/1103#issuecomment-248046168, so far it is working with PostgreSql 9.4 and code merged from PR https://github.com/qcubed/framework/pull/1104

**Comment by vaibhav-kaushal** [comment]
@spekary We can close this, if we are keeping a backlog of what needs to be improved in 3.1
