### ISSUE TITLE
Proposed Feature: option to generate(and use) setters and getters instead of magic _get and _set 

### ISSUE THREAD

**Issue by demike** [qcubed/framework#145]
I recently profiled an application using the QCubed orm layer.
The result was very interesting.
We had a huge query. The query itself ran fast but the most time was spent in the __get and __set methods of the generated orm classes.

So i replaced the most occuring calls to __get with calls to added get* set* methods
and the performance increase was amazing.

So I think there should be an option for the orm generator to generate set* and get* methods
instead of using __get and __set

**Comment by spekary** [comment]
Continued in #300
