### ISSUE TITLE
MVC type auto-update of viewer controls

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#289]
@scottux I think you mentioned this idea before, and I would like to revisit it. I am having a need to do something like node.js does, with automatically updated views into data, whether they are in separate windows or users on other machines. (e.g. automatically refresh a QDataGrid when the data it is showing is changed by a user on another computer). Here is my thought:

* Have individual controls register themselves as viewing particular db tables
* Have the Save() method save off a timestamp indicating that the db table changed 
* Whenever a control is drawn that is also viewing tables, it would read the latest timestamp for that table and save it in a local variable (which will make it part of the formstate)
* Have forms use a javascript timer to periodically poll the controls, which would then check the timestamps on the tables they are watching, and call Refresh() if the timestamp is newer

A lot of the infrastructure for this is already there. Just wondering if there is a desire to have something like this part of the core.

**Comment by olegabr** [comment]
IMHO, it is already implemented in the v3
