### ISSUE TITLE
alpha-3.0 branch

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#314]
I pushed up a new branch alpha-3.0. This is a merge of the following branches and bugfixes:

master
bug-237
bugfix-ExtendedAssnTable
feature-AddKeyEvents
feature-AddSelectorToEventBase
feature-apidoc
feature-CheckBoxColumnFixes
feature-DbSpeedImprovement (with fixes)
feature-listitem-for-empty-option-189
feature-ManyManyTypeTables
feature-qqselect-with-no-pk
feature-RecursiveTransaction-127
feature-SimpleTableUpdate
feature-v3 
bugfix-QSoapService

Plus some additional composer code and readme changes. Hopefully this will be incentive to get everyone on the new branch, as all the merging has been done, and appears to be working well. See the Install.md for composer installation instructions.

I would also like to propose that we go to a new model of development. This literally took days to merge. Having all those open feature branches was not as easy as first proposed. I think we need to go to a model where we merge features fairly quickly into master so they don't get stale. Waiting for a release is not working. We never even merged 2.3.0 back into master.

This is also a call to anyone who has new code that might be an API change. Now is the time to get it in, since we are going to a new version number. 

Also, lets move this to master fairly soon, once it shows itself stable, and then we can get it on to packagist.

**Comment by vaibhav-kaushal** [comment]
Closing this since we are about to get to beta!
