### ISSUE TITLE
Create a way to customize the mapping between UI objects and DB types

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#346]
Currently we rely on the templates to create this mapping. We should have some other way of specifying how db types map to ui objects during codegen, both on a global level, and a per-form level.

To do this, we may need the ui objects themselves to publish what kind of db types they support, and how they get initialized and updated. For example, a QListBox and QAutocomplete can both support a reverse reference (Many-to-one), but they do it very differently.

**Comment by olegabr** [comment]
IMHO, it is implemented in v3 already
