### ISSUE TITLE
exp-QWatcher

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#383]
I created a exp-QWatcher branch, an experimental feature based on the current alpha-3.0. This feature lets you tell a control to watch a particular table or tables for changes, and when a change happens, the control will automatically redraw. Redraw happens even if the control is in a different window from the currently active form, or even if the database was changed by a user on another machine. See the install/project/controls/QWatcher.php file for usage and setup instructions. The short answer is that you need to set up a special database table, or install APC or APCu. after that, you turn on a flag for each table object that you want to watch, and then tell the controls what table(s) each control should watch. Generally, you will be telling datagrids to watch particular tables.

Currently the system checks for changes whenever there is an ajax call, and will piggyback the redraw of controls on that ajax call. If a change is detected, all watching controls are redrawn, and all other QCubed windows in the same browser are notified to check for changes as well. The only thing it can't currently do is notify other browsers that a change happened (see below).

I am putting this forward now to let you all evaluate the approach and contribute. Major things to do are:
* Create an examples page
* Create a push-update strategy

Regarding the push update strategy, there are many approaches to that, and I think Socket.IO and Ratchet are the two sites that have it pretty well figured out. Bottom line, to really do a good job, apache is not a good answer for serving up socket connections to browsers. It has too much overhead. The best strategies seem to involve extra server configuration to use either a different port, or intercept web requests before they get to apache, and pass off WebSocket requests to a different process. I am hoping we could set up a simple web socket repeater on qcu.be, but have no idea how to do it. A repeater simply broadcasts a message to all the other listeners on a channel. That would be enough to tell everyone to check the database for changes and update if needed.

**Comment by olegabr** [comment]
IMHO, it is implemented in v3 already
