### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by RO-29** [qcubed/framework#444]
I just started using facebook new(ok not new!) engine and it just blew my mind.. in terms of speed and everything. I tried it only on bare php project without using any framework or cms.As of now HHVM supports 20 popular frameworks and cms inclusive and unfortunately Qcubed is not in the list. http://hhvm.com/blog/4841/compatibility-update

I really want this super fast engine to be integrated with this awesome framework(Qcubed).I am posting this here as to know if anybody here has tried using HHVM for Qcubed and if yes then what are their experiences and if not ,can anybody guide me as to how can I start working on it to integrate with qcube.

**Comment by olegabr** [comment]
hhvm is in our travis tests already!
