### ISSUE TITLE
Security attributes for many qcubed files are incorrect

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#458]
In the already merged commit
https://github.com/vaibhav-kaushal/qc-framework/commit/8c35573ea15e923801f3766f31f15df9b40f3cc0 there are a lot of sentences like that: ` .gitignore 100644 → 100755`

It should be fixed back to 644 for all files listed in this commit.

**Comment by olegabr** [comment]
it still applies. we need to fix file access permissions before release.

**Comment by vaibhav-kaushal** [comment]
May be we should have a script which sets up the permissions for QCubed files in deployment. We can use the same for development too.

I use git for deploying one of my projects and FTP for another. The script could be used on the server as well and git deployment post-push-hook can be used to call the script. It would be good!

**Comment by spekary** [comment]
The whole deployment script thing is a big amount of work.  I suppose it should be written in PHP so that its cross-platform. We would need to look into PHP technologies that can put files and set permissions. Perhaps with an eye to supporting more than just FTP. SFTP, WebDav, etc.
