### ISSUE TITLE
Make a separate qcubed_app project from the current project directory

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#461]
@spekary, what do you think about to make the example project - the starting point of the new qcubed application to be the first-class qcubed subproject, as the `framework` is now: `qcubed/sample_app` for example.

The workflow for starting the new qcubed project whould be to download the sample_app archive, unpack it, run the `composer install` in it, that would install the qcubed dependency, and then run the usual qcubed installer from it, or do a manual configuration.inc.php config.

Now it is frustrating to have inside the framework itself :-)

**Comment by spekary** [comment]
Following up on this. Please see the current install instructions for beta 3. It now uses a create project command with a custom installer. Our custom installer currently just creates a special installer for plugins, but it could be changed to also ask questions during the project creation process that could be used to create the initial configuration file. See https://getcomposer.org/apidoc/master/Composer/IO/IOInterface.html for what you can do from the command line during a composer install process.

**Comment by olegabr** [comment]
we have https://github.com/qcubed/app-starter now. The aim of this issue was exactly that - a different starter project to start develop qcubed application. Closing it.
