### ISSUE TITLE
Front Controller and QPage

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#472]
Is it possible to implement QPage plugin  https://github.com/qcubed/QPage into core alpha 3  to have some possibility for one page front controller, and other pages as forms  . My suggestion is to not change default Qcubed mechanism but to have  option for this. I tried to implement this solution    https://github.com/qcubed/framework/wiki/Front-Controller-Pattern   but finished with object inheritance problems and i think this example isn't tested on alpha or dynamic classes should be qpanels but not forms .Is there some idea or example for implementing this ?. I made  mod_rewrite setups and i have some working code but i have strange double forms in pages, not as i expected.

**Comment by olegabr** [comment]
#612 is related.
