### ISSUE TITLE
Codegen Configuration

### ISSUE THREAD

**Issue by neuroticimbecile** [qcubed/framework#491]
Hi All,

How does one configure the qcubed code generator:

1. to use "QueryString" instead of "PathInfo" in generated *EditFormBase.class.php and *ListFormBase.class.php files?

2. to change the value of "$this->mct->TitleVerb" in the generated *_edit.tpl.php files?
e.g. use the word "Add" instead of "Create"?

3. to change the generated words "Listing All" in *_list.tpl.php into e.g. "Showing"?

4. to make "$this->mctTable->lstColumn_Create()" create QListBoxes whose items are sorted by Names (as defined in the "__toString" function in Table.class.php) instead of Values?

5. to make "$this->mctTable->calColumn_Create()" (without time component) create QCalendar instead of QDateTimePicker?

Thanks!

**Comment by spekary** [comment]
V3 solves these problems. 
1. The codegen_settings.xml has an option to choose QueryString vs. PathInfo.
2 and 3. The NavBar is configurable to control the title verb and other top level items on a page.
4. Override the ModelConnector function that creates the listbox.
5. Override the column create functions in the list connector.
