### ISSUE TITLE
AJAX Dashboard is broken

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#531]
Selection of item from the list here (in my installation)  does nothing: http://localhost/qcubed3/vendor/qcubed/framework/assets/php/_devtools/panel_drafts.php

**Comment by vaibhav-kaushal** [comment]
As said earlier, I think it should survive. We can create a repo with the current version's (2.2.3) template and have other repos for other template sets. 

Or should we have one huge repo with multiple templates in its subdirectories?

**Comment by vaibhav-kaushal** [comment]
However, the main issue (as stated in the title) seems to have been solved. If it still exists, please reopen.
