### ISSUE TITLE
Where is the forum

### ISSUE THREAD

**Issue by siepmannj** [qcubed/framework#571]
Hello, don't know where to ask. if it is the wrong place, please delete it.

Since the forum on qcu.be is gone, where can I post questions?

thanx in advance,

Jan

**Comment by vaibhav-kaushal** [comment]
Have a look here: http://www.qcubed.in/help

For normal questions, you can ask them on StackOverflow using QCubed tag. You can use this link: http://stackoverflow.com/questions/ask?tags=QCubed+PHP

**Comment by neuroticimbecile** [comment]
I think it would reach a wider audience if the real qcubed site was updated
with that information.

Just a thought,
-eric

**Comment by vaibhav-kaushal** [comment]
Where should we mention it? On the top menu?

**Comment by neuroticimbecile** [comment]
In the "Community" block on the home page.
and at the very top of the "Forum" page.

Thanks,
-eric

**Comment by neuroticimbecile** [comment]
Hi All,

Did anyone ever get around to update the original qcubed site?
qcu.be still does not provide proper information on where the new forums
are.

I think we need info about the new forums at least on a very noticeable
part of the home page, and on top of the forums page.

(On a side note, I've had a bad experience with my very first qcubed
question in stackoverflow.com, people seemed too eager to vote you down,
and take a long while to unvote after the question has been improved. Just
saying.)

Regards,
-eric
