### ISSUE TITLE
Potential bug in QRadioButtonList using QAjaxAction?

### ISSUE THREAD

**Issue by kmott** [qcubed/framework#592]
I was working on setting up a simple form that has a set of RadioButtons that I want the user to be able to select only one from.

Here's what my QForm looks like:
```php
  class RadioButtonListForm extends QForm {
    protected $strPageTitle = 'QRadioButtonList Test';
    protected $objRadioButtonList = null;
    protected $btnSubmit = null;

    protected function Form_Create() {
      $this->objRadioButtonList = new QRadioButtonList($this);
      $this->objRadioButtonList->AddItem(new QListItem('Radio 1', 1));
      $this->objRadioButtonList->AddItem(new QListItem('Radio 2', 2));
      $this->objRadioButtonList->AddItem(new QListItem('Radio 3', 3));

      $this->btnSubmit = new QButton($this);
      $this->btnSubmit->Text = 'Submit';
      $this->btnSubmit->AddAction(new QClickEvent(), new QAjaxAction('btnSubmit_Click'));
    }

    public function btnSubmit_Click($strFormId, $strControlId, $strParameter) {
      QFirebug::log($_POST);
      QFirebug::log($this->objRadioButtonList->SelectedValue);
    }
  }
```

When I have the btnSubmit as a QAjaxAction(), here's what the $_POST looks like:
```php
array(
    ['Qform__FormState'] => 'daf600f467a62be383fc9115bb0eabb1'
    ['Qform__FormId'] => 'RadioButtonListForm'
    ['Qform__FormControl'] => 'c2'
    ['Qform__FormEvent'] => 'QClickEvent#a1'
    ['Qform__FormParameter'] =>
    ['Qform__FormCallType'] => 'Ajax'
    ['Qform__FormUpdates'] =>
    ['Qform__FormCheckableControls'] => 'c1'
)
```

When I have the btnSubmit as a QServerAction(), here's what the $_POST looks like:
```php
array(
    ['c1'] => 2
    ['Qform__FormState'] => '680067365a5af9cfd89927456ea1dedb'
    ['Qform__FormId'] => 'RadioButtonListForm'
    ['Qform__FormControl'] => 'c2'
    ['Qform__FormEvent'] => 'QClickEvent'
    ['Qform__FormParameter'] =>
    ['Qform__FormCallType'] => 'Server'
    ['Qform__FormUpdates'] =>
    ['Qform__FormCheckableControls'] => 'c1'
)
```

Note that the QServerAction() has my strControlId in the $_POST parameters, so the control now has $this->objRadioButtonList->SelectedValue set correctly to whatever radio the user has selected.

Is there something I'm missing to get the QRadioButtonList control to work with AJAX?

**Comment by spekary** [comment]
It may be a bug. I have done a lot of work in qcubed.js to fix these kinds of issues, and alpha3 has these fixes.

The $_POST parameters are the key, and they should appear the same. The missing ['c1'] => 2 is definitely the problem. I would tell you to copy the qcubed.js file from alpha3 and try replacing yours with it, but it might be too different. Theoretically it should work.

**Comment by kmott** [comment]
Thanks for the quick reply @spekary.  I tried swapping out the qcubed.js from alpha-3.0, and it still didn't work.  I'm under a tight deadline, so I will have to use QServerAction for now, and do more debugging later.  Thanks!

**Comment by spekary** [comment]
Step through getPostData in qcubed.js. That is where it is supposed to gather up the control values for ajax calls.

**Comment by kmott** [comment]
Okay, I need some help.  I did some rudimentary debugging, and found that line 173 of my qcubed.js has this:

```javascript
if ($j(this).attr("checked")) {
```

If I change it to the below, it seems to sort of work, but each item in the control has Selected=true, instead of just the one the user has actually selected.
```javascript
if ($j(":checked").attr("id")) {
```

I'm going to keep going, but if anybody has pointers, I would really appreciate it. :-)

**Comment by spekary** [comment]
Which version are you using. In the current master, that is not on line 173.

**Comment by kmott** [comment]
@spekary, I'm running 2.2.2 currently.

**Comment by kmott** [comment]
After looking at 2.2.3 ZIP archive, it looks like it has the same problem.  I think the master has the changes around lines 230 or so.

**Comment by kmott** [comment]
Pulling from master seems to have resolved the issue...  Glad it was that easy :-).  Maybe we should do a quick 2.2.4 release, so people grabbing the latest-and-greatest (prior to 3.0 being ready) won't run into this?
