### ISSUE TITLE
Version 2.2.3 not working with jQuery version 1.9.1+

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#595]
I am trying to use a certain page in QCubed with Twitter Bootstrap (TwBs) framework. TwBs requires jQuery 1.9.1 to work properly. When I upgrade version of jQuery from 1.7 to 1.9.1 in my QCubed installation (version 2.2.3), almost all JS events fail to register (I believe that is because of qc.loadJavaScriptFile function but not very sure about it). 

Also, AJAX does not work. Replacing both jQuery files (and UI files) and qcubed.js from alpha-3.0 branch also does not work. I get plain XML in return. ANyone has any idea about this? Can we backport the jQuery upgrade to version 2.2.3?

**Comment by matthiaz** [comment]
Vaibhav,

I'm using bootstrap on jquery 1.7 without a problem on qcubed 2.2.3. I
haven't had the need to upgrade jquery to 1.9. I know this is not a
solution for qcubed because it should be able to work with 1.9. But it
might help you with setting up your project on jquery 1.7.

Regards
Matthias

2015-02-06 11:26 GMT+01:00 Vaibhav Kaushal <notifications@github.com>:

**Comment by vaibhav-kaushal** [comment]
Which version of Bootstrap are you on?

**Comment by vaibhav-kaushal** [comment]
I am trying to get Bootstrap v3.3 working with QCubed 2.2 but it just wouldn't work. For me, it is extremely important that it does before we take the time out to release v3.0 (what haven't we already?). It is a huge bottleneck in my flow right now and I would really appreciate any help in this direction.

**Comment by matthiaz** [comment]
Vaibhav,

I'm using bootstrat v3.2 on maxcdn
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
"></script>

I did make some alterations to the default css classes of QButton,
QTextBox, QListBox, and so on... I would love to make a wiki entry about
how to do all this but I haven't got the time.

I'm just now starting up a new project with the same bootstrap and qcubed
version. If I come up with errors, I'll be sure to post the fix here.

Regards
Matthias

2015-02-06 15:44 GMT+01:00 Vaibhav Kaushal <notifications@github.com>:

**Comment by spekary** [comment]
I am working on a Bootstrap plugin for v3. The reason for the lack of release is the refactoring work. My goal for v3 is for people to be able to create new projects from v3 without worrying about them breaking in v3.1. The Bootstrap plugin work in particular has pushed the refactoring on the basic drawing system, in that bootstrap mostly uses classes to style things, and also expects particular kinds of objects to be laid out in particular ways.

There is more to do, but I think most of it can wait. On the docket are:
- Refactor javascript processing to remove the eval(). That can wait.
- Refactor form templates to separate out the control creation from the process of loading the control with data. This will let you load new data into a form through ajax without having to recreate the whole form, and the current structure is not good at that. This can wait.
- Rename MetaControl to ModelController, but have a code gen option that lets you name this what you want, so for backwards compatibility, MetaControl can be used. I think the name makes sense, and the nice thing is that the 'mct' prefix still works ;-) I don't think this can wait. It shouldn't take too much time to do that though.

I would suggest basing new projects on alpha3. I realize it has been changing a lot lately, but major changes are almost complete. I am using the code in two production environments as well and it seems to be working well.

I will put up the bootstrap plugin shortly.

**Comment by spekary** [comment]
Bootstrap upload is a little delayed. Some of it is dependent on the direction of the QListControl refactoring that I attempted. I need a day or two.

**Comment by vaibhav-kaushal** [comment]
Are we using traits for the drawing part? I think that is what is needed to separate the drawing properly. QCubed core could use a particular trait by default, a developer can create a new trait(s) to make a separate theme. (Like if I want Zurb foundation as the UI framework, I can write my trait, change a config and that starts working)! By that time, I am trying to figure out why TwBs is playing devil for me. Something good should come out of it all, I hope. :hurtrealbad:

**Comment by vaibhav-kaushal** [comment]
@matthiaz Which version of the jQuery library are you using in your copy?

**Comment by matthiaz** [comment]
define ('__JQUERY_BASE__', ' http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js');
	define ('__JQUERY_EFFECTS__', ' http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js');

**Comment by spekary** [comment]
@vaibhav-kaushal Not traits. The new drawing code simply uses static functions at the lowest level to draw HTML tags, and then builds it up from there. Any PHP code can call into the static code to draw a structured tag now. No more hand-coding of html is needed, and the code will come out in two forms: a nicely structured developer version, and a compact minimized version.

Traits in general should be used sparingly. They are really designed to encapsulate an idea that can span different kinds of objects. Hack requires that traits be self-checkable. In other words, they shouldn't relay on code or members that are not listed in the trait itself. I think this is a generally a good practice as we think about using traits. Traits do have a mechanism of abstract methods to call outside of themselves though.

I might be using a trait in the Bootstrap code, but its more to get around the problem of needing to create an examples page without being able to modify project objects.

**Comment by spekary** [comment]
Initial bootstrap plugin code is now up. See the plugin_bootstrap repo. Install directions for composer are there.
