### ISSUE TITLE
Control persistence changes

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#603]
@spekary 
2. I mentioned a change in how Persistence works. I need #602 to be able to do this step. This change will mean that you can do this:

$objControl->SaveState = true
and the object will have the ability to restore its visible state. I don't know if anyone uses the current persistence mechanism, but its a memory pig, and its design goals were to be a kind of caching of controls with complex data. Its not really the right way to cache that data, and the implementation is cumbersome. The new version will only save the minimum amount of info to restore the visual state, and not the underlying data, which I think is what most people need. It also makes it easy to save the state of all the controls in the whole application for a particular user, and then restore that state when they log back in, so they feel like nothing changed between logins.

**Comment by spekary** [comment]
#617
