### ISSUE TITLE
Rename the MetaControls concept to the ModelController

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#605]
@spekary 
4. The final effort will be to resolve the name of MetaControls. I would like to change it to ModelController. The nice thing about this is that the 'mct' prefix can stay the same, so most user code will not need to change much. The name is reflective of what it does, using the language of MVC. This work will need a change of name to the new MetaParams and MetaControl designer dialog. But again, this is all name changing an not really different code.

**Comment by spekary** [comment]
Fixed #620
