### ISSUE TITLE
QTextBox: ValidateTrimmed be dropped?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#610]
We have two properties currently (in alpha) which can be used to trim a textbox's Text - AutoTrim and ValidateTrimmed. 

While AutoTrim can automatically trim the very Text of the textbox, ValidateTrimmed would only run validations over only trimmed version of the text but does not update the value of `strText`. I think this is both redundant and confusing. 

Shouldn't we drop ValidateTrimmed? Or deprecate it at least?

**Comment by spekary** [comment]
ValidateTrimmed should be removed. I don't know why we would want to validate a trimmed version of the text, without actually trimming the displayed text.

**Comment by vaibhav-kaushal** [comment]
I will proceed with that.
