### ISSUE TITLE
Remove QUpdateUtility

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#625]
Remove the deprecated QUpdateUtility and the manifest.xml file.

**Comment by vaibhav-kaushal** [comment]
:+1:

**Comment by vaibhav-kaushal** [comment]
Is this still pending?

**Comment by spekary** [comment]
Yes. Can wait for beta.

**Comment by vaibhav-kaushal** [comment]
I think this can be closed as well, since we are going to use Composer for updating the framework after the release.

**Comment by spekary** [comment]
It is a note to actually remove it from the code. Its still in the code and still shows up on the start screen.

**Comment by vaibhav-kaushal** [comment]
What is stopping the delete? I wanted to remove it but since I am still studying the code, I did not want to go there.

**Comment by vaibhav-kaushal** [comment]
I think this one has been done as well. Deleting the link in #1001
