### ISSUE TITLE
Do not Render if not an object

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#636]
Hi all. This is my very often problem when rendering objects in form. I have a lot of if-else statements where i am creating new objects dynamically. So everytime i got 'Trying to get property of non-object' error with E_NOTICE level  in $this->obj->Render() . Instead of changing php error level how we can overcome this in render function or is there another solution?. My idea is to have static Render like QApplication::Render  of statically call Render method with object name as parameter . SO object existence will be checked first .

**Comment by spekary** [comment]
I like your idea. There are currently some render helper functions, like _p(). You could create a _r($obj, $strMethod, $options) and do just what you are describing. Also, there is a PreferredRenderMethod attribute that should be used instead of strMethod if strMethod is null.

**Comment by spekary** [comment]
#641
