### ISSUE TITLE
Qcube coaching request for proposal

### ISSUE THREAD

**Issue by andrewbauman** [qcubed/framework#637]
Hello all!
I know I am soliciting but hear me out and direct me to the proper channel.
I have been using mysql for a data backend and access 2007 for a front end over 8 years. I run a 12 employee wood finishing business. I started using quickbooks to do my bookkeeping but found that my business model was different than most. I hired a custom programer but fell prey to escalation of commitment. I managed to get the root password to the mysql database he was using and created my own workorder tracking system using access for front end. Several years ago I decided that the open source route was what I wanted to support and went on a search for a rapid dev php platform I could use as effectively as MS access without the head aches of noncentralized applications. I settled on qcube and have successfully code gen against parts of my database and am working on some simple forms. However the work I need done is large and I am pressed for time. 
So my thought would be to win a business relationship with a "Coach" that is familiar with qcube. I would anticipate working on the back end according to action plans we mutually work out. The "Coach" would then setup a login/audit/permission structure, assist with technical difficulties with the goal in mind that I would be trained in my particular application so that I can extend the functionality by adding tables and actions to forms. I am using codaid to edit my php code currently and have successfully set up netbeans. I am not well versed in css or java script but have hacked my way to implement changes and can use google very well. My "coach" would also be prepared to implement upgrades as necessary to stay current. I require responsive web apps in html5 because mobile is where its at. I am impressed with the potential of this platform and would like to learn more!

**Comment by kmott** [comment]
Hi, I'd love to help out Andrew. Send me a direct email if you are interested: kyle@klmh.co

**Comment by spekary** [comment]
@kmott, great! Its about time someone around here made a little money :+1: 

@andrewbauman, From your basic description, qcubed should do the job. You want a no frills data-driven website. You want to be able to easily modify the data structure in the future. You want to go as quickly as possible from data structure change to ui-implementation. You want small screen support. For the small-screen support, see the developing Bootstrap plugin. Once alpha3 goes to beta, which is soon we all hope, that plugin should help you easily implement forms that are phone compatible.

**Comment by andrewbauman** [comment]
@kmott, Hi!
I always am doing cross referencing of any online personalities. your klmh.co resolves to KLMHosting.net is that your company?
