### ISSUE TITLE
Use of undefined constant MYSQLI_ON_UPDATE_NOW_FLAG

### ISSUE THREAD

**Issue by StevenWarren** [qcubed/framework#647]
Hey guys, 

Been away from the project for a while and thought I would catch up by installing the 3.0 alpha release using composer. Got through the installation and tried to run codegen against a small database I have setup when I received this error:
```
Use of undefined constant MYSQLI_ON_UPDATE_NOW_FLAG - assumed 'MYSQLI_ON_UPDATE_NOW_FLAG'

Error Type: E_NOTICE

Source File: /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/database/QMySqliDatabase.class.php Line: 686

Line 681:    
Line 682:    			$this->SetFieldType($mixFieldData->type);
Line 683:    
Line 684:    			// Special situation that we take advantage of to automatically implement optimistic locking
Line 685:    			if ($mixFieldData->type == MYSQLI_TYPE_TIMESTAMP &&
Line 686:    					$mixFieldData->flags & MYSQLI_ON_UPDATE_NOW_FLAG) {
Line 687:    				$this->strType = QDatabaseFieldType::VarChar;
Line 688:    				$this->blnTimestamp = true;
Line 689:    			}
Line 690:    		}
Line 691:    
Call Stack:

#0 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/database/QMySqliDatabase.class.php(686): QcodoHandleError()
#1 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/database/QMySqli5Database.class.php(93): QMySqliDatabaseField->__construct()
#2 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/database/QMySqliDatabase.class.php(131): QMySqli5DatabaseResult->FetchFields()
#3 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/codegen/QDatabaseCodeGen.class.php(751): QMySqliDatabase->GetFieldsForTable()
#4 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/codegen/QDatabaseCodeGen.class.php(491): QDatabaseCodeGen->AnalyzeTable()
#5 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/codegen/QDatabaseCodeGen.class.php(386): QDatabaseCodeGen->AnalyzeDatabase()
#6 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/includes/codegen/QCodeGenBase.class.php(227): QDatabaseCodeGen->__construct()
#7 /Applications/MAMP/htdocs/mytestsite.loc/vendor/qcubed/framework/assets/php/_devtools/codegen.php(14): QCodeGenBase::Run()

https://github.com/qcubed/framework/commit/fc1fafce2c0d9fcb825323169e637dbdb2857559#diff-e6096ba470c31dc7113e151281541b49
```

I see that the code was added with this commit  [https://github.com/qcubed/framework/commit/fc1fafce2c0d9fcb825323169e637dbdb2857559#diff-e6096ba470c31dc7113e151281541b49] . It appears we were fixing issues with resolving timestamps for generating optimistic locking.  I researched the [PHP Mysql constants](http://php.net/manual/en/mysqli.constants.php) and was unable to find MYSQLI_ON_UPDATE_NOW_FLAG listed, nor have my searches provided any help. Is this a bug, or am I missing anything?

Environment:
MAMP PRO Version 3.0.7.3
PHP Version 5.6.2
MySQL 5.5.38 - Source distribution
QCubed 3.0.0 Alpha Release (QCubed 3.0.0)

**Comment by spekary** [comment]
Hmm. This may be a sticky problem. This is currently listed in PHP Storm as a MysqlI constant, but I can't find it officially documented online. It may be an undocumented flag, and so may have been removed in PHP 5.6. It is in 5.5. Its supposed to detect that the field is set up to automatically update the timestamp. We may need to remove that, or define it ourselves if its not defined (8192 is the value). If removed, we can fall back on the PGSQL method of notifying ourselves of an auto-updating timestamp value.

I think for now we should define it if its not defined, and see if it works. Its pretty useful.

**Comment by spekary** [comment]
Just to be sure, do you have the mysqli extension installed in your PHP, and if so, what is the version?

**Comment by vakopian** [comment]
I have php 5.5.12 with mysqli extension installed, and I also had a problem with that flag (I had to comment it out to be able to run alpha 3). We could do a `if (defined())` check before using the flag, but the fact that it's not documented at all tells me we should refrain from using it?

**Comment by vaibhav-kaushal** [comment]
I could not find anything related to this flag either. All that Google shows are complaints.

**Comment by spekary** [comment]
Hmm. OK then, not sure why its working for me, but we should do it the same as PGSQL then if the define is not present. I can try to code that and have you guys test it.

**Comment by StevenWarren** [comment]
Sorry, been out of pocket attending a family members 50th wedding anniversary. Yes I have MySQLi extension installed. Details:
MysqlI Support	enabled
Client API library version	5.5.38
Active Persistent Links	0
Inactive Persistent Links	0
Active Links	0
Client API header version	5.5.38
MYSQLI_SOCKET	/Applications/MAMP/tmp/mysql/mysql.sock

I will try some time tomorrow to see if I see any ill effects using "if (defined())" maybe something like 
```PHP
if(!defined('MYSQLI_ON_UPDATE_NOW_FLAG')) {
    define("MYSQLI_ON_UPDATE_NOW_FLAG", 8192);
}
```

**Comment by spekary** [comment]
Try #659
