### ISSUE TITLE
starting new project

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#666]
hello everyone,

I'm using qcubed for nearly 3 years for some customer specific applications,
it's a great tool, many thanks to all the people that created and now contribute 
to this project, for me it's the fastest and easiest way to build web applications. 

Now I'm planning a new project (web based CRM like application) and I'm not sure
if I should start it with version 2.2 that I'm actualy using or begin with version 3.0.

If I start my project with 2.2 wil I have to refactor everything when I switch to 3.x
or should I start with the actual 3.0 master to avoid this ?

many thanks

norbert

**Comment by vaibhav-kaushal** [comment]
I would say - start with 3.0. 2.2 is quite different from 3.0 and upgrading can get a bit messy.

**Comment by nlomb** [comment]
thanks, Ill try it ...

I'm reading the discussions in 3.0 constantly, 
so I think I have to update my installation very often
