### ISSUE TITLE
The script tried to execute a method or access a property of an incomplete object not working inside my ubuntu

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#668]
@Caal Saal VI

My script working well on my windows xampp localhost

But got error this error "The script tried to execute a method or access a property of an incomplete object" on my ubuntu localhost.

Here is the different for both ubuntu(ini1) and windows(ini2) php.ini

http://sitepreview.ourace.com/compareini.php?s=1&g=551ce4d6995c3551ce4d69962a

I not really think this code problem since it working on my windows

http://stackoverflow.com/questions/29428807/the-script-tried-to-execute-a-method-or-access-a-property-of-an-incomplete-objec

**Comment by nlomb** [comment]
@olegabr

hello oleg,

had this once, reason was a deleted column in the forms and database and not running codegen ...

hope this helps ...

if not, please give me some more info about the script or what it is supposed to do
so i can try to reproduce this error on my local server.(ubuntu 14.04).

Happy Easter!

norbert
