### ISSUE TITLE
Create Beta Branch?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#678]
Are we there yet? Can we create a Beta branch now and start testing? 

@vakopian and @spekary its your call. :blush:

**Comment by vakopian** [comment]
It's really @spekary's call, I haven't started testing alpha 3 in a serious way yet

**Comment by spekary** [comment]
Its fine. Or just rename it. There is no real reason to have a separate branch. We don't intend for alpha3 to live on.

**Comment by spekary** [comment]
Done.
