### ISSUE TITLE
Dialogs and Alerts

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#695]
Its been on my todo list for a while to do some mods to the dialog code, and to enable some alerts in the code. The priority in this work would be to try to keep as much of the current functionality as possible, while improving efficiency, adding alerts, and looking for opportunities to be able to bring up alerts and dialogs by making a simple call, rather than needing to assemble a QDialog subclass and making it a member of the form.

Dialogs currently are hidden html that are always on the page. You show them by calling Open(), which basically just makes them visible. With a lot of dialogs, this can clutter the DOM. Also, doing it this way doesn't save all that much traffic across the wire, as most of the dialog would get redrawn when showing anyways in order to populate the data.

An alternate way to do this would be to have an entire dialog be sent through ajax when needed. This is partly done by the deprecated ShowDialog code that is there now. 

In order to support creating and removing dialogs on the fly, and not needing to make them objects you set up in Form_Create, we will need to make some changes to how controls get inserted. I may be mistaken, but I don't think the current architecture supports dynamically adding controls to a form at the top level of the form. Currently they must be child controls of a control that is already up. That could be fixed with some changes to qcubed.js.

To do simple dialogs, like alerts and confirmations, I think a modification to qcubed.js could be done to put up a dialog with a string and some buttons, and then fire an event that shows what button were clicked, and that would automatically removed the dialog from the screen at the same time.

The thing I want to think through is how to do this in a way that could be over-ridden to support something like Bootstrap dialogs through the bootstrap plugin.

**Comment by vaibhav-kaushal** [comment]
I think by all means, we should have a guide to write plugins.

**Comment by spekary** [comment]
That guide is mostly done. Its there in the examples pages for beta3. There are some minor changes that need to be added due to the recent code generator classes added by @vakopian .

**Comment by spekary** [comment]
This is now implemented in beta3. See the QDialogBase::Alert function. You can now create on-the-fly alerts and simple confirmation dialogs without putting the dialog into the form state. The dialog will get injected into the dom temporarily, and then removed when the dialog is closed.

**Comment by spekary** [comment]
Note that the current examples point to a dialog plugin that does not currently exist in the 3.0 code. This should be fixed.
