### ISSUE TITLE
PHP7 Testing

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#697]
We need to see if our code is compatible with PHP7. I know of one problem we are going to have, that they have removed the php echo tag ```<?=``` Seems like the developers there really did not think through that decision, as all the online discussion about why they did that has to do with all the other short tag variations, and nothing to do with this particular tag. I suspect they will put it back after people complain, but for now, we will probably have to change everything back to ```<?php echo```

**Comment by vaibhav-kaushal** [comment]
I always thought ```<?php echo``` was a much better option because it is not a shortcut and is a determined command to the interpreter. They are not going to take away ```<?php``` tag ever, I guess :smile:

**Comment by vaibhav-kaushal** [comment]
On a second note - I am not sure if the database adapters are already ported to PHP7 or not. Unless those are ported properly, there would be no way for us to be sure if our code works with PHP7 the way it should or not.

**Comment by alexelhamdi** [comment]
so till now not supported yet right ?

**Comment by spekary** [comment]
Unknown. HHVM works though.

**Comment by olegabr** [comment]
accept the https://github.com/qcubed/framework/pull/859. It makes qcubed to be tested against all PHP versions.

**Comment by spekary** [comment]
We can't just put php7 in the test without someone testing it locally. We shouldn't break the test in order to force us to fix it. 

We now have to deal with PHP7 and hhvm support, as we have two diverging versions of the language, both with features that will break earlier versions.

QCubed 3 has been targeted for a baseline of php 5.4, and I think we should keep it that way. We need to fix whatever needs fixing to make PHP7 work, but for now, not use the additional features that would break backwards compatibility, like the spaceship or null-coalesce operators, unless we are version checking.

Moving forward, I think we should start with PHP7/HHVM specific functionality in the model code generation. Since the beginning, we have had infrastructure that does type checking. Both languages now have built-in type checking mechanisms, but both handle it differently. That is difficult for most frameworks to deal with, but since we do code generation, we can put some flags in codgen_settings.xml to generate different models depending on the language targeted. Some low-level code, like Query and the database adapters might need some tweaking and version specific changes to make that all work.

The other problem to fix there is the use of __set and __get instead of setters and getters, as is being discussed in #300. The PHP7 and HHVM optimizers can make the code much faster when using setters and getters.

**Comment by olegabr** [comment]
@spekary, look at it: https://travis-ci.org/qcubed/framework/builds/98723300

PHP7/mysql, PHP7/pgsql and hhvm/mysql configurations already has a succes with qcubed tests )

You can safely merge https://github.com/qcubed/framework/pull/859. It does not breaks any test.

**Comment by spekary** [comment]
Wow, that is great news. It means that codgen is working, with the <?= short tag. It was unclear from the PHP7 documentation whether that was going to be included in the release, since they were removing the other other short tags.

**Comment by matthiaz** [comment]
@spekary 
There was indeed a RFC that proposed the removal of *alternative* short tags.
https://wiki.php.net/rfc/remove_alternative_php_tags
I think this may have been wrongly interpreted by some bloggers. 

According to the documentation: 
http://php.net/manual/en/language.basic-syntax.phptags.php

7.0.0	The ASP tags <%, %>, <%=, and the script tag <script language="php"> are removed from PHP.

So yeah:  <?= and <? will remain available . Hooray

**Comment by tomVertuoz** [comment]
Hi,
As I understand it, QCubed beta 3 seems to work with PHP 7.
Does the beta 3 is stable enough to use in your projects in production ?

Thank you for your valuable work, QCubed is a very good framework.
Regards.

**Comment by vaibhav-kaushal** [comment]
I am using it in one of my production sites. There a little bit of problems with Proxies, mostly because of the way I used it but the rest is working. It is always advisable to do a test run on a staging server before putting it up on a production site.

**Comment by spekary** [comment]
I too use it on a production site, and have been using it since the beginning of development of v3. That said, we are still in beta, and there may be some possible destabilizing changes yet to come.

I am currently concerned about how model list connectors are working. I am not sure that having the control create columns is the right way to do it, vs. having the enclosing panel create the columns. I have been using it, and it feels cumbersome the way it is coded now, but I need to do more research.

That is the only possible major change I foresee. Other than that, we are working on fixing bugs, and getting the examples to work.
