### ISSUE TITLE
Right Click not working in v3.0?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#699]
I am trying to port my existing application from 2.2 to 3.0 and the one thing I am clueless about is why does it not let me right click on the page. When I do, I see the ajax wait icon for sometime (like a flash) and then it disappears and nothing happens. was a right click handling code written somewhere in 3.0 for the user side? If yes, then where?

**Comment by kukrik** [comment]
Hi @vaibhav-kaushal!  I do not know if I understood you clearly. Just go to the Drafts Form View, choose another table and hit a few lines on "Edit" and then you can right  click to see it :).

**Comment by vaibhav-kaushal** [comment]
@kukrik I think English is not your first language. I will try to explain in simple way: 

1. I install QCubed 3.0 
2. I move all files from old project to new project folder
3. I run new (version 3) project. Project is running. 
4. I right click on page (in Google Chrome) in new project. 
5. Wait icon comes and goes and nothing happens.

**Comment by kukrik** [comment]
I understand! I have not done it yet... I would also like with you to know  :) ... Good question to @spekary!

**Comment by vaibhav-kaushal** [comment]
I found out the issue. I had left design mode on which was causing the issue in the live project.

**Comment by kukrik** [comment]
What was the problem? You can specify? Good to know!

**Comment by vaibhav-kaushal** [comment]
I had not disabled design mode!!
