### ISSUE TITLE
Recovery from framework deletion

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#700]
@vaibhav-kaushal accidentally deleted the framework repo. At this point, github support has restored it, but there is still a remnant problem. When it was deleted, all local repos became descended from StevenWarren/framework, the parent of the qcubed/framework.

I have asked github support to fix this, but have not heard back from them yet. In order to fix it yourself, you will need to delete your fork on github and then fork it again. Renaming the fork will not work. I am not sure how this will affect any uncommitted branches on your personal fork. Be sure to make a local copy of the fork on your personal computer before deleting your github fork to be sure you don't lose anything.

**Comment by spekary** [comment]
From github support:


The qcubed repository has been made the root again. If there's any trouble with your forks still please let me know.

Thanks,
Steven!

**Comment by vaibhav-kaushal** [comment]
@spekary Thanks for taking the efforts to write to them to restore the repo. Really sorry for the mistakes I committed.

**Comment by vaibhav-kaushal** [comment]
Closing this issue.
