### ISSUE TITLE
Problems with the Composer install of 3.0 beta

### ISSUE THREAD

**Issue by davidmclark1** [qcubed/framework#705]
hello.
I thought I would try an install of the 3.0 Beta on a Windows box runing WAMP.   I have never used Composer but managed to get it installed and running.   however, when I try to install Qcubed it tells me I need an Token for the GIt API.   I followed instructions and retrieved the Token .   Says it goes in a auth.json file in my Composer AppData file.  What does that json file look like?   Can you give me an example.  

Thanks

**Comment by spekary** [comment]
See

https://github.com/composer/composer/issues/3542
