### ISSUE TITLE
How to export file xml from QDataGridColumn to zip file for download from a button QCubed/QCodo

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#706]
@alvin zefanya

its my code .. any can help me guys :(

public function btnZipDownload_Click($zip, $key, $base) {

foreach($this->GetAllControls() as $objControl) {

if (substr($objControl->ControlId, 0, 11) == 'chkSelected') {

$zip = new ZipArchive;

if ($zip->open('somefile.zip') === TRUE) {

for ($i = 0; $i < $zip->numFiles; $i++) {

if ($objControl->$couples) {

$couples[]=array('filename'=>'./somenewfile.ext','localname'=>$zip->getNameIndex($i));

}

}

}

foreach ($couples as $couple) $zip->addFile($couple['filename'],$couple['localname']);

$zip->close();

}

}

}

}

http://stackoverflow.com/questions/30912084/how-to-export-file-xml-from-qdatagridcolumn-to-zip-file-for-download-from-a-butt

**Comment by ubs** [comment]
A bit more context/details will help. At present I can only hazard a guess at what is being asked here.

**Comment by spekary** [comment]
There are quite a few problems with this code. I think the first thing you should do is to set up an interactive debugger that will let you step through your code. Essentially, this means:
1) Install php and a web server (like apache) on your local computer.
2) Install xdebug
3) Install an IDE, like PHP Storm, Eclipse, or something similar, that will let you interactively step through your code and set breakpoints.

Those things take some time, but if you are going to develop PHP code, you really need to do it. It will save you time in the long run. Stepping through your code, you will see that $couples is undefined when you first use it, and your first use ```$objControl->$couples```, I don't think it is doing what you think. Perhaps you mean ```$objControl->Checked```?
