### ISSUE TITLE
PHP Storm Licensing

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#712]
JetBrains offers free licenses for open source developers of their PHP Storm product. I am trying to renew the license, and wondering if anyone else would like a license. They are asking for the number of licenses we want, since they are moving to an individual licensing model.

**Comment by kukrik** [comment]
I have very little time, and contributed, but I would also be interested. I use NetBeans. How does that sound? Or I do not qualify for this criterion?

**Comment by vaibhav-kaushal** [comment]
I do

**Comment by vaibhav-kaushal** [comment]
Any updates on this @spekary ?

**Comment by spekary** [comment]
@kukrik Please send mea private email to shannon@ryaa.org

**Comment by vaibhav-kaushal** [comment]
I think this can be closed. Please reopen if needed.
