### ISSUE TITLE
readme files

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#716]
A reminder to make sure we update all the readme files, and include new ones that are missing. I noticed that the codegen directory has no readme file. They should document the purpose of each directory, and spell out whether the directory should be included in deployment.

**Comment by vaibhav-kaushal** [comment]
I do not think any of the codegen process needs to be on the server. In case you have different views, I'd like to know the reasons. :)

**Comment by spekary** [comment]
Not sure what you mean. I am referring to the project/includes/codegen directory .

**Comment by vaibhav-kaushal** [comment]
I think this one was taken care of.

**Comment by spekary** [comment]
This is still open. @olegabr has made a point that QCubed is useful for teaching people how to program in PHP. We need to expect new programmers to use the framework. Someone needs to go through all the readme files, make sure they make sense for they exist, and correctly describe each directory.

For example, the readme's in the assets directories are all the same and repeated in every subdirectory. That should instead be moved to the parent directory, and the description be improved.

**Comment by vaibhav-kaushal** [comment]
@olegabr Which directories do you think should have a Readme file in them?

**Comment by olegabr** [comment]
@vaibhav-kaushal I need some time to see it.

**Comment by vaibhav-kaushal** [comment]
@olegabr What other places should we put README files at?

**Comment by olegabr** [comment]
These two should explain how to see examples and run tests:
 - assets/php/examples
 - assets/php/tests

Here we should explain how to use cache directory for non-image files:
 - assets/cache

The main framework folder:
 - includes

```
includes/i18n/_README.txt -> includes/i18n/README.md
```

the readme file in includes folder should explain each subfolder usage, or, preferably, each subfolder should have it's own readme file.

**Comment by vaibhav-kaushal** [comment]
I am not sure about assets/cache yet! Will have to go through the code to get a grip on that one! 😕

**Comment by olegabr** [comment]
About `assets/cache` I mean that in a readme file we should encourage user to use this directory not only for images, but any other web-accessible files he needs to cache somewhere.

**Comment by vaibhav-kaushal** [comment]
@spekary and @olegabr I am stopping the work on this one for now. I will start documentation with scratch and when I encounter this one on the way, I will start working on it again. I believe, we need a Wiki for that.

**Comment by vaibhav-kaushal** [comment]
Is this still open? Or can we close this issue?

**Comment by olegabr** [comment]
we can close it IMO
