### ISSUE TITLE
Install Testing

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#721]
I updated the installation instructions for composer. Please see the beta-3 Install.md file and try it out. It should be able to do a simple online composer installation, enough to get to the point where the qcubed installer can take over.

Also try the QCKEditor installer.

**Comment by aadityabagga** [comment]
Hi,

I was able to install using given method. Output was as follows:
http://pastebin.com/PDnkHaGf

However, when I try to launch the plugin manager, I get an error:
~~~~
 Error in PHP Script /qcubed3/vendor/qcubed/framework/assets/php/_devtools/plugin_manager.php
require_once(/var/www/html/qcubed3/vendor/qcubed/framework/includes/framework/QPluginInstaller.class.php): failed to open stream: No such file or directory
~~~~

Also, when I try to install plugin_bootstrap, I get following error:
~~~~
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                        
  - Installing qcubed/plugin/bootstrap (dev-master 3857c0c)
    Cloning 3857c0c961d65b3b0d13c61f6c0cfcd1a248d50e

> QCubed\Devtools\Installer::postPackageInstall
Copying qcubed/plugin/bootstrap files.
Script QCubed\Devtools\Installer::postPackageInstall handling the post-package-install event terminated with an exception


                                                                                                                                                      
  [ErrorException]                                                                                                                                    
  session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/html/qcubed3/vendor/qcubed/framework/includes/_d  
  evtools/Installer.php:29)                                                                                                                           
                                                                                                                                                      


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]


PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Cannot modify header information - headers already sent by (output started at /var/www/html/qcubed3/vendor/qcubed/framework/includes/_devtools/Installer.php:29)' in /var/www/html/qcubed3/vendor/qcubed/framework/includes/framework/QApplicationBase.class.php:1009
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'Cannot modify h...', '/var/www/html/q...', 1009, Array)
#1 /var/www/html/qcubed3/vendor/qcubed/framework/includes/framework/QApplicationBase.class.php(1009): header('Cache-Control: ...')
#2 /var/www/html/qcubed3/vendor/qcubed/framework/includes/qcubed.inc.php(54): QApplicationBase::OutputPage('')
#3 [internal function]: __ob_callback('', 9)
#4 {main}
  thrown in /var/www/html/qcubed3/vendor/qcubed/framework/includes/framework/QApplicationBase.class.php on line 1009
~~~~

composer.json file in install directory looks like the following:
http://pastebin.com/E9PpmEmn

**Comment by kukrik** [comment]
I do not know whether to give the right advice. @spekary is the right man!

I may have made a kind of...

First composer:
```
{
	"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/qcubed/framework"
        }
    ],
	"require": {
		"php": ">=5.4.0",
		"qcubed/framework": "dev-beta-3.0"
	},
	"minimum-stability": "dev"
}
```
Another composer:
```
{
	"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/qcubed/framework"
        },
        {
            "type": "vcs",
            "url": "https://github.com/qcubed/plugin_timepicker"
        },
        {
        "type": "vcs",
        "url": "https://github.com/qcubed/plugin_autocomplete2"
        },
        {
        "type": "vcs",
        "url": "https://github.com/qcubed/plugin_phonetextbox"
        },
        {
        "type": "vcs",
        "url": "https://github.com/qcubed/plugin_datatables"
        },
        {
        "type": "vcs",
        "url": "https://github.com/qcubed/plugin_bootstrap"
        },
        {
        "type": "vcs",
        "url": "https://github.com/qcubed/plugin_ckeditor"
        }
    ],
	"require": {
		"php": ">=5.4.0",
		"qcubed/framework": "dev-beta-3.0",
        "lastcraft/simpletest": "dev-master",
        "qcubed/plugin/timepicker": "dev-master",
        "qcubed/plugin/autocomplete2": "dev-master",
        "qcubed/plugin/phonetextbox": "dev-master",
        "qcubed/plugin/datatables": "dev-master",
        "qcubed/plugin/bootstrap": "dev-master",
        "twbs/bootstrap": "~3.3@dev",
        "qcubed/plugin/ckeditor": "dev-master",
        "ckeditor/ckeditor": "4.*"
	},
    "suggest": {
        "ezyang/htmlpurifier": "dev-master"
    },   
	"minimum-stability": "dev"
}
```
With regard to the plugin manager into, then this is a problem right now, I wanted to inform @spekary...

The rest of the plugins are working for me!

Perhaps maybe my samples?

**Comment by kukrik** [comment]
I have  to @spekary questions about QCKEditor installer, but this later...

**Comment by spekary** [comment]
Fix #725. Thank you for testing. Only CKEditor is working with the new plugin system. This is all in flux, but getting there.

If we want to put the plugins in Packagist, there is a little problem. Packagist expects the package name to only be 'qcubed/name'. We can't name something 'qcubed/plugin/name'. This problem is that this is ALSO the directory structure. So, we will be forced to have a directory structure that looks like:
- qcubed
  - framework
  - plugin_ckeditor
  - plugin_bootstrap
etc.

Rather than:
- qcubed
  - framework
  - plugin
    - ckeditor
    - bootstrap

The drupal project is working this way, so its pretty clear this is what we all have to do. I will be fixing this up today.

**Comment by aadityabagga** [comment]
Hi,

If I try to do a ```composer update``` in the directory I had installed QCubed 3 beta, this is what I get:

~~~~
  [Composer\Downloader\TransportException]                                                                          
  The "https://api.github.com/repos/qcubed/plugin/bootstrap" file could not be downloaded (HTTP/1.1 404 Not Found)  
~~~~

After removing plugin_bootstrap data from composer.json and re-running ```composer update``` this is what I get:

~~~~
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                        
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - qcubed/framework dev-beta-3.0 requires qcubed/composer dev-master -> no matching package found.
    - qcubed/framework dev-beta-3.0 requires qcubed/composer dev-master -> no matching package found.
    - Installation request for qcubed/framework dev-beta-3.0 -> satisfiable by qcubed/framework[dev-beta-3.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
~~~~

**Comment by spekary** [comment]
Today I changed the installation process to a Composer installer plugin. You will either need to delete the directory completely, and start over with a ```composer create-project ...``` command, or see the new additions to the composer.json file in the app-starter repository, and merge those in with yours. It should work then.

The composer installer is now in the qcubed/composer repository. It needs to be installed before anything else gets installed. In order to do this, I had to require it from the framework project, or it might get installed afterwards. The app-starter project is what sets everything up correctly.

The ckeditor plugin should work as well. The other plugins still need to be fixed, so the bootstrap plugin definitely is not working right now. It is really in a very beginning stage anyways. If anyone wants to help, all you need to do is to create an ```install``` directory and put (or create) the subclass files in there. Also, change the ```type``` in the composer.json file to ```qcubed-plugin```.

**Comment by aadityabagga** [comment]
Was able to do a new install.
http://paste2.org/7atvKOFZ

~~~~
$ tree /var/www/html/qcubed-3/ -L 3
/var/www/html/qcubed-3/
|-- composer.json
|-- composer.lock
|-- index.php
|-- project
|   |-- assets
|   |   `-- _readme.txt
|   |-- generated
|   |   |-- connector_base
|   |   |-- drafts
|   |   |-- form_base
|   |   |-- model_base
|   |   |-- qcubed.inc.php
|   |   `-- _readme.txt
|   |-- includes
|   |   |-- app_includes
|   |   |-- codegen
|   |   |-- configuration
|   |   |-- connector
|   |   |-- controls
|   |   |-- framework
|   |   |-- i18n
|   |   |-- model
|   |   `-- plugins
|   |-- qcubed.inc.php
|   `-- tmp
|       |-- cache
|       |-- plugin.install
|       `-- plugin.tmp
|-- qcubed.inc.php
|-- README.md
`-- vendor
    |-- autoload.php
    |-- composer
    |   |-- autoload_classmap.php
    |   |-- autoload_namespaces.php
    |   |-- autoload_psr4.php
    |   |-- autoload_real.php
    |   |-- ClassLoader.php
    |   `-- installed.json
    |-- lastcraft
    |   `-- simpletest
    `-- qcubed
        |-- composer
        `-- framework

28 directories, 16 files
~~~~

Will try out the ckeditor plugin.

**Comment by kukrik** [comment]
So far, good progress! 
But it ckeditor plugin does not work yet. I get the error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package qcubed/plugin/ckeditor could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
After, change the type to qcubed plugin, this plugin does not work. I laid back to type "type": "library", it worked...
@spekary, it should look?

The next question - and I can not find a good solution on how to bring out the ckeditor config.js? As an example from CKeditor API:
```
CKEDITOR.replace( 'editor1', {customConfig: '/custom/ckeditor_config.js' });
```
This solution will provide more options for configuring ckeditor. 
@spekary. You're a smart man, you know how to provide good suggestions and ideas!

Last question - I noticed that you might not have noticed one error. I am here just to copy:
```
<script type="text/javascript">qc.baseDir = "/qcubed-3"; qc.jsAssets = "/qcubed-3/qcubed-3/vendor/qcubed/framework/assets/js"; qc.phpAssets = "/qcubed-3/qcubed-3/vendor/qcubed/framework/assets/php"; qc.cssAssets = "/qcubed-3/qcubed-3/vendor/qcubed/framework/assets/css"; qc.imageAssets = "/qcubed-3/qcubed-3/vendor/qcubed/framework/assets/images"; </script>
```
My development "__SUBDIRECTORY__" = "/qcubed-3" is such. There is a double "/qcubed-3/qcubed-3/etc/etc/...".  Previously, it was not... This is a mistake and needs to be repaired!

Thank you in advance!

**Comment by spekary** [comment]
For the first problem, the installation instructions were wrong. I fixed the Readme.

Change ```"qcubed/plugin/ckeditor": "dev-master",```
to ``` "qcubed/plugin_ckeditor": "dev-master",```

in the main composer.json file.

**Comment by spekary** [comment]
I cannot recreate problem 3.

For #2 there are a couple of solutions. CKeditor has a ton of options, all configured in javascript. It is best to configure it in javascript, rather than creating a bunch of PHP options, but I suppose if someone wanted to they could scrape the docs like we do in other situations.

Anyway, if you want to change the global settings, in the QCKEditor.php file, override the ```registerFiles()``` function and add a custom js file. That file would look just like the config.js file supplied with CKEditor, but with customizations. Since it loads after the provided file, it will replace the CKEditor.editorConfig function.

To do as you suggested and configure each instance of CKEditor separately, each instance could replace the strJsReadyFunc parameter with a  function that calls ```CKEditor.replace()```. And, you would also need to include a js file that has all the parameters that you want to replace it with.

The ultimate would be to use a scraper to generate all the configuration settings in a PHP version, and then that would generate a js object that contains all the options and sends it into the strJsReadyFunc in the GetControlJavaScript function, but that would be a lot of work.

Feel free to help by coding my suggestions as examples.

**Comment by kukrik** [comment]
Let's talk more about the problem of 3. Previously, I had not noticed this mistake. But this bug in past available. Not just one place, but everywhere...
If you made a lot of changes inside QFormBase.class.php. I understand that the updates are always required for development.
Specifically -  "__VIRTUAL_DIRECTORY__" is empty, you should not be out of it. I added the screenshots,you will get a better understanding of...
![screen shot 2015-07-27 at 4 07 56](https://cloud.githubusercontent.com/assets/2853034/9025995/9137cff8-3926-11e5-887d-ce467783ca07.jpg)

**Comment by kukrik** [comment]
Now we are talking about a CKEditor. You are right to say that the global settings are not good. I'm the same opinion.
I also agree that it is better to set the editor all configured in javascript.
I have made the preparations for the two editors. Please see the screenshots:
![screen shot 2015-08-01 at 22 55 13](https://cloud.githubusercontent.com/assets/2853034/9026300/3a5cfdf4-3933-11e5-968e-3d25d3e38412.png)
@spekary. Are you still confident that Ajax cannot use (your quote: currently cannot use ajax)?  In this example, runs QAjaxAction.

I thought, and can not provide a good solution. Sure it is that I have a little experience. How, for example, to write "$this->textEditor->???????->(filename and path);", "$this->txtEditor1->???????->(filename and path );", etc... It would be quicker and more convenient solution! If we put, for example, files such as project/includes/plugins folder standard.config.js, simple.config.js etc...

For this ??????? it is necessary to make the function and placed in the GetControlJavaScript function, etc...

@spekary! What do you think about this? Or, you will see a totally different solution or another trend?

**Comment by spekary** [comment]
#748 fixes 3

**Comment by spekary** [comment]
I have updated the plugins for data tables, phonetextbox, time picker to use the new installer. See the readme file for simplified install instructions.

**Comment by spekary** [comment]
Trying to update it through ajax might be difficult. Like if you set the Text to something new. I haven't done a lot of testing of trying to manipulate the control after it is created. AjaxActions probably work OK. The question is whether an AjaxAction will also redraw the control correctly if the control is modified after being created.

**Comment by spekary** [comment]
Try this. I don't have time to test it. Maybe you can code a test:

```
$this->textEditor = new QCKEditor ($form);
$this->textEditor->ReadyFunction = 
    sprintf('function(){CKEDITOR.replace("%s", config1);}', $this->textEditor->ControlId);
```
And then your javascript file would be: 
```
var config1 = {
   configOption = 'blah';
   etc....
}
```

**Comment by vaibhav-kaushal** [comment]
I used the qcubed/app-starter and it is working fine. I am working on the guide in the meantime. This one looks fine. However there are some issues that I am facing with the class loading.
