### ISSUE TITLE
Model class paths for autoload missing?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#764]
I installed QCubed 3.0 using https://github.com/qcubed/app-starter. It worked fine (except that I had to set the values of ```__SUBDIRECTORY__``` and ```__DOCROOT__``` manually for them to be correct).

However, after code-generation, my model classes are not loading. What might be the reason? I could not find QQN.class.php either :confused: .

**Comment by spekary** [comment]
Something has caused the templates to fail in the middle. Will need some debugging.

**Comment by vaibhav-kaushal** [comment]
I think I have found out the problem. A little bit more debugging is required. I think it is because we are serving warnings and errors both as errors and then the if condition here in https://github.com/qcubed/framework/blob/beta-3.0/assets/php/_devtools/codegen.php

```
			if (!$strErrors) {
				foreach (QCodeGen::GenerateAggregate() as $strMessage) { ?>
					<p><strong><?php _p($strMessage); ?></strong></p>
				<?php }
			}
```
causes the trouble. My schema has some foreign keys without single column index on them. Hence I get some warnings (which are all set as errors) and so, the aggregator part never runs.

**Comment by vaibhav-kaushal** [comment]
This issue was fixed. Closing thread. Please see #765 for solution.
