### ISSUE TITLE
Beta 3.0 Ajax Parsing Failed popup not working

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#767]
If the AJAX response is a HTML document (i.e. the error page), then we get the alert message saying something similar to 

*Ajax parsing failed. Error will open in a new popup*. 

However the new popup never opens.

**Comment by spekary** [comment]
Need more info. Does this happen all the time? Are popups enabled in the browser?

**Comment by vaibhav-kaushal** [comment]
Popups are enabled in the browser. Till now, I have observed that it happens always. However, I believe more test runs are needed to reproduce the behaviour.

**Comment by vaibhav-kaushal** [comment]
I haven't come across more such failures. Will reopen if needed.
