### ISSUE TITLE
What is QApplication::$Minimize?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#790]
@spekary I am going through some tough parts of the new release and I see that a lot of points where we are rendering HTML, we take ```QApplication::$Minimize``` into consideration. What exactly is this variable? The provided Doc comment was not helpful either!

**Comment by spekary** [comment]
It takes out much of the white space in the resulting HTML, and all the comments. If you leave it off, you will see a much prettier HTML output, which is useful for debugging.
