### ISSUE TITLE
QSelect2ListBox plugin

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#808]
@Poojaa Ingale

I have installed QSelect2ListBox plugin in frame work but it is giving error like "Call to undefined method QSelect2ListBox::getJqControlId() in D:\XAMPP\htdocs\DX-HRM4.0\includes\qcubed\plugins\QSelect2ListBox\includes\QSelect2ListBoxGen.class.php on line 191"

i have checked that function is present there. Please let me know if someone has occurred same problem & has solution on it

http://stackoverflow.com/questions/33460080/qselect2listbox-plugin

**Comment by spekary** [comment]
Looks like he is using old code.
