### ISSUE TITLE
Allowing front-end tests via Selenium WebDriver

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#817]
Hello folks, 

In my company we are trying to automate certain tests for our application. While we can work with the unit testing in a better way (was looking a bit into codeception too, but I am new to this), we can enable front-end testing with tools like Selenium WebDriver which can automate UI-based functional testing.

One of the prime requirement of such tools is to identify the element on which actions (click, hover, keypress etc.) have to be taken. We have a dynamic ID system wherein most of the elements can change their IDs according to where they are placed on the form and the order in which they are created. This is good, but can cause quite some problems with the testing process. 

The feature that I am trying to build here is the following set: 

1. Addition of a ```data-``` attribute on **QControlBase** rendered HTML. We can assume it to be ```data-qcontrol-testing-id``` (or something similar).
2. Addition of a property (and a variable) which can be used to hold the value of this attribute.
3. The attribute can be enabled by a global config (assume we call it ```__FRONTEND_TEST_MODE__```).

When the testing mode is defined and switched on in the configuration file, the rendered HTML will contain the attribute and the value that we want to assign. The element can then be picked up by the testing tool using XPath. 

It will allow the application to be more testable. It would not hamper any of the pre-built applications or other behaviour either and can be enabled or disable via a global switch so that we do not emit those attributes in the production environment.

What do you say? (Especially @spekary , since he is doing most of the work for 3.0 release).

**Comment by vaibhav-kaushal** [comment]
**UPDATE**: Created pull request #818 for the same.

**Comment by matthiaz** [comment]
@vaibhav-kaushal I find this very interresting. I would love to see how you do tests on a qcubed project.

**Comment by vaibhav-kaushal** [comment]
@matthiaz Some of my pages were having troubles with control IDs because there were extra elements being created depending on various factors. So either we specify control IDs within the code (which can cause massive headache) or introduce a ```data-``` attribute on our own for the controls that we need to test without having to worry about our own application or someone else's code. Hence, came up with the changes. 

It would be great if you can see the pull request and give your feedback/suggestions.

**Comment by matthiaz** [comment]
@vaibhav-kaushal Yeah, I've looked at the committed code. It looks OK. 
But I do wonder if the same thing can be achieved using    
    $control->SetCustomAttritbute('qcontrolTestingId',$value);

How do you use that TestingId property in selenium? Is this something you add in production code? Or only in selenium?

**Comment by spekary** [comment]
QCodo is a layered framework, so usually there is a way to do things without impacting the core. Core should change in order to make it possible to do special circumstances that are not currently possible, but I think this falls under the category of something you can already accomplish without impacting the core.

As I understand it, you want to add a data-... attribute to all controls in a way similar to how control ids are generated? The QControlBase __construct function shows how the control id is generated, and so you could override this in your project/includes/controls/QControl.class.php file and do what you want there.

SetCustomAttribute is now SetHtmlAttribute, but does the same thing. Your constructor in QControl.class.php would look something like:

```
public function __construct($objParentObject, $strControlId = null) {
   parent::__construct($objParentObject, $strControlId);
   $strTestingId = $this->GenerateTestingId();
   $this->SetHtmlAttribute("data-testingId", $strTestingId);
}
```
Also, if you don't like how control ids are created, you can always override that here, or in your QForm.class.php file by overriding GenerateControlId(). 

The code you put in your pull request should go in your own QControl.class.php file.

**Comment by vaibhav-kaushal** [comment]
I agree, that what you are saying is correct. I can do this by altering my own QControl file. Nothing wrong with that. 

However, there is nothing I am doing to **generate** the testing IDs. They have to be set manually (that's the whole purpose of testing - identify elements and fire actions and test results; if I am generating the testing IDs then I probably cannot *predict* them and that fails the very purpose). 

Second, this feature is controlled by a global variable so to switch it on or off is quite easy.

Third, I believe this provides an opportunity to introduce quick testing on the developer's parts. In my team, it is easy to tell how to select the element - there is just one attribute and one value I have to tell the testers. So in case someone comes up with "how I test my app with selenium webdriver", there is a one-stop easy solution to answer that.

@matthiaz Indeed that method can be used. The TestingId attribute is a wrapper around that to protect from spelling mistakes and allowing easy switching on/off of the feature.

**Comment by spekary** [comment]
I see. So, why does it need to be in QControlBase, rather than your own private QControl?

**Comment by vaibhav-kaushal** [comment]
Because it gives QCubed developers a quick way to enable testing of their applications with frontend test automation tools like Selenium WebDriver.

**Comment by vaibhav-kaushal** [comment]
What do we do with this?

**Comment by spekary** [comment]
One danger in any code base is code-bloat. We should be careful about what we add to the core, especially if it requires turning things on and off using defines The more conditional code, the more confusing it gets and harder to maintain. The bar should be high for what goes in the core. It should be something that is likely everyone will use. It should also be something that becomes part of the Examples. And it should be something that really is not doable using a plugin.

While your code is a useful thing for some developers to do, it does not seem likely that everyone will do it. This still seems like something that is application specific to me. There are other front-end drivers for testing. Plugins are really there for this kind of addition. Or, it could be a how-to article. Perhaps if it becomes popular enough to the point that we use it to baseline test the core, it could be moved to the core. 

The bootstrap plugin is a case in point. Very useful, but not necessarily something that everyone will do.

The value of what you have done is not in generating the data- attribute. That is trivial for someone to do, and would be very application specific. Its more in you sharing your experience with automated testing using this tool. A plugin gives you an opportunity to describe how to install and use the tool with qcubed, and give examples, without needing to put the examples into the core examples area. And future developers don't need to worry about maintenance.

**Comment by kukrik** [comment]
But in any case, it would be very useful plugin and examples. Tests are necessary for the developer to be sure.

Or at least, a comprehensive article with the screenshots.

**Comment by vaibhav-kaushal** [comment]
@spekary I believe you are right here. Missed the point about code bloat. Will try to make it a plugin.
