### ISSUE TITLE
Doubled newlines in multiline QTextBox in beta-3.0 on QServerAction

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#823]
Hello, 

I am testing my site with the new version and I notice that newlines are getting doubled in multiline QTextBox after submitting via QServerAction. So if I write:

```
this is
a test (no newline at the end)
```

in the textbox and submit then after the action is taken, the textbox contains:

```
this is

a test (no newline at the end)
```

The server response (raw) contains the following for the innerHTML of the textarea:

```
this is
&NewLine;a test &lpar;no newline at the end&rpar;
```

This does not happen on QAjaxAction.

**Comment by koopa** [comment]
I tested this quickly here and the same problem occurs.
ServerAction requests have been made from a NT platform, so the newlines in the data sent were represented as `\r\n`. 

After the QApplication::HtmlEntities($this->strText); call in QTestBoxBase's GetControlHtml function, the string was actually encoded as `'1\r&NewLine;2\r&NewLine;3\r&NewLine;'`

The same handler via an AjaxAction request however revealed that a newline was actually encoded as only a single line feed with no carriage returns in it at all. Consequently for XHRs that means no duplication and all is good.
Not sure exactly why that is - is jquery possibly unifying newlines under the hood for all requests it makes?

Replacing the byte sequences `\r\n` and `\r` to `\n` would probably do the trick for normalizing the newlines before applying the htmlentities conversion. Or the htmlentities call needs to be adjusted a bit. ENT_HTML5 seems to not treat \r\n, \n and \r equally - but we need that, don't we?

**Comment by vaibhav-kaushal** [comment]
I would say we do need that. It is breaking quite a number of things and things can be unacceptable if people start getting all their posts with huge gaps between paragraphs!

I am going to look into qcubed.js to see if there is evil in there. Some testing and experimentation is needed. :sweat:

**Comment by spekary** [comment]
Not likely a qcubed.js problem. Server actions avoid qcubed.js and use HTML to send the data straight to the $_POST variable. Probably something simple. I will take a look.

**Comment by spekary** [comment]
See #824
