### ISSUE TITLE
Extending qapplication

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#831]
Hi all,
is there a method of extending qapplication properties in runtime when i'am  creating form class , for example login sessions , cookie checks but i don't want to change prepend.inc.php. I want to create new session property of qapplication object and check values in runtime  . Or to make login plugin or widget in one file and insert when i need it. And will be a good idea to make some visual chart of qcubed system how it works and how objects , events or whatever is created when Form:run is executed

**Comment by spekary** [comment]
Can you be a little more specific. Session properties go in $_SESSION. They are not part of the Application object. You can change session properties any time and they will be remembered.

Every time the program enters, QApplication is constructed. QForm gets read from the serialized form object, which could be stored in the session, in a database, or wherever else you want. So change in QApplication do NOT persist, but changes in $_SESSION and QForm do persist.

Inserting controls is a little tricky, and there is an example on this in the Examples pages (changing parent). You must insert controls into a control that is already on the form, or the control will get added at the end of all the current controls. Another way is to add the control during Form_Create, set UseWrapper to true, and then Visible to false. Be sure to render the control in your template. When the control is not visible, it will render a stub div that is a place marker for where the control will appear when you set Visible to true.

**Comment by vmakre** [comment]
I don't want to mess too much in prepend.inc.php , there are places for initialization, for static methods , working with languages , etc. but maybe better idea is to put everything we want in plugin and call autoloaded classes . When you change a lot of code in one project this become a problem for future projects if you want to reuse same functionalities. Will be good idea for one big bundle plugin for user/group  login, authentication and registration   , to implement from some free project ?.

**Comment by spekary** [comment]
You are saying you would like to create a plugin to do authentication?  Yes, I think a plugin would be appropriate for that.
