### ISSUE TITLE
Merging Cells Vertically

### ISSUE THREAD

**Issue by cortesjuan** [qcubed/framework#832]
How can I to merge the cells in a QDataGrid column vertically? For example: Only one "Me"  and only one "BC"

ColumnA          ColumnB         ColumnC
1                             Me               AB
2                             Me               BC
3                             You              BC
4                             He                FG

**Comment by matthiaz** [comment]
I can understand you'd dont't want to repeat the ME, but I can't understand why you wouldn't want to repeat the BC.
Either way, you can achieve this but overloading the default value of the addcolumn.

Normally you would do something like:
```
$yourdatagrid->MetaAddColumn(QQN::Table()->ColumnA);
$yourdatagrid->MetaAddColumn(QQN::Table()->ColumnB);
$yourdatagrid->MetaAddColumn(QQN::Table()->ColumnC);
```
If you want some special treatment for certain columns you can use:
```
$yourdatagrid->MetaAddColumn(QQN::Table()->ColumnA, array('Html'=>'<?= $_CONTROL->GetSpecialColumn($_ITEM)?>');
```

$_CONTROL = your datagrid class
$_ITEM = your current object 

In your datagrid class you can then define this method:
```
public function GetSpecialColumn($objItem) {
    static $objPrevious = false;
    if(is_object($objPrevious) && $objPrevious->ColumnA == $objItem->ColumnA) {
        //looks like the same object as last time
       return '';
    } else {
        //not the same object, display it
        return $objItem->ColumnA;
    }
}
```

Side note: you don't have to use MetaAddColumn, you can do the same with AddColumn.
Good luck!

**Comment by cortesjuan** [comment]
Thank you very much! The column C with BC repeated is only part of example, 
I suppose that treatment would be the same as that applied to column B

**Comment by cortesjuan** [comment]
a small correction, without it the code does not work...

public function GetSpecialColumn($objItem) {
    static $objPrevious = false;
    if(is_object($objPrevious) && $objPrevious->ColumnA == $objItem->ColumnA) {
        //looks like the same object as last time
       return '';
    } else {
         //assign the new value to old value
         $objPrevious  = $objItem;
        //not the same object, display it
        return $objItem->ColumnA;
    }
}

**Comment by matthiaz** [comment]
You are right. You have to set the $objPrevious... 
Sorry I never tested the code I typed, but I'm glad you got it to work.

**Comment by spekary** [comment]
QDataGrid2 in beta3, based on QSimpleTable, allows you to specify row and column spans. Easiest is to subclass the column and override the necessary routines. One column is going to need to put out a rowspan, and the other column is going to need to print out nothing, because it is spanned.

This is an example that I use to create header spans. Its specific to my app, but should demonstrate what I am talking about.

```
	public function GetHeaderCellParams () {
		$a = parent::GetHeaderCellParams();

		if ($this->intColSpan > 1 &&
				$this->objParentTable->CurrentHeaderRowIndex == 0) {
			$a['colspan'] = $this->intColSpan;
		}
		if ($this->intRowSpan > 1) {
			$a['rowspan'] = $this->intRowSpan;
		}
		return $a;
	}

	protected function ShouldDraw() {
		if (!$this->IsHidden()) {
			if ($this->strSubcolumnName &&
				!$this->strName &&
				$this->objParentTable->CurrentHeaderRowIndex == 0) {
				return false; // don't draw
			}
			elseif ($this->intRowSpan > 1 &&
				$this->objParentTable->CurrentHeaderRowIndex == 1) {
				return false;
			}
			return true;
		}
		return false;
	}

	/**
	 * Prevent rendering a header cell when blocked by a colspan or rowspan
	 * @return null|string
	 */
	public function RenderHeaderCell() {
        if ($this->ShouldDraw()) {
			return parent::RenderHeaderCell ();
        }
        return null;
    }

```

**Comment by cortesjuan** [comment]
Thanks you! I'll try with this option.
