### ISSUE TITLE
QAutocompleteTextbox inside QDatagrid

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#833]
hello all,

first of all: I'm just playing around with V3.0, looks realy great,
(ok, just codegen and looking around directory structure ...)

__many thanks to all contributors__

this is still on V2.2.3 and I don't think I will change this in the near future  ...

I'm trying to use QAutocompleteTextbox inside a QDatagrid and have problem with event handling,
see attached file
[event-problem.txt](https://github.com/qcubed/framework/files/52173/event-problem.txt)

maybe someone can help me with this ...

norbert

**Comment by spekary** [comment]
JQuery UI's autocomplete does not send a traditional change event. Do this:

```
AddEvent(new QAutocomplete_ChangeEvent(), new QAjaxAction());
```

**Comment by nlomb** [comment]
@spekary 

thanks a lot, 

will try tomorrow and then report

greetings from germany

Norbert

**Comment by nlomb** [comment]
@spekary || all
hello,

just tried, didn't work ...
AddEvent(new QAutocomplete_ChangeEvent(), new QAjaxAction());

where can I find the supported / available events ?
should I look into the sources ?

BTW: I'm using jQuery v1.7.1 jquery.com and jQuery UI - v1.9.2

**Comment by spekary** [comment]
1. See the JQuery UI objects examples page for working examples of how to use the autocomplete widget. Online here: http://examples.qcu.be/assets/_core/php/examples/other_controls/jq_example.php
2. Use the latest JQuery and JQueryUI. They are bundled with beta 3. Those versions are quite old. jQuery UI is at v. 1.11 now.
3. That should have worked. You did put in a routine name inside QAjaxAction call, correct? 
4. Debug at the javascript level first. You can set breakpoints inside the qcubed.autocomplete.js file, in the .on("autocompletechange") handler and see that changing the autocomplete will get there. If not, you likely have a javascript error somewhere. Note that a javascript startup error basically shuts down all the javascript for the widgets on the page.

**Comment by spekary** [comment]
Also, all the supported and available events are listed at the top of the sources. See QAutocompleteGen.class.php. The ones in the "Gen" class map directly to the jQueryUI events for autocompletes as listed in the jQueryUi documentation.

**Comment by nlomb** [comment]
hello,
I just replaced my old (2.2.3) jquery*.js with those from V3.0 and tried again, still not working ...
maybe we misunderstand here:
the autocomplete itself works like a charm but the following QAjaxAction
``` php
$objControl->AddAction(new QAutocomplete_ChangeEvent(),  new QAjaxAction("txtFieldvalue_Change"));
```
is not called. I want to use "QAutocomplete" to edit a field and save the changed value on leaving the widget (focus out). this works in the same script with "normal" QTextbox.

Any tip is welcome

BTW: with V3.0 which is the preferred place to put the custom application?
I like to hold all libraries under DOCROOT/lib and put my own scripts under DOCROOT/app and DOCROOT/app - subdirs for different parts of the application.
In DOCROOR/lib I have also eg. PHPMailer and fpdf.

sorry if I bother you

**Comment by spekary** [comment]
Could be a number of things. 
- Calling QAjaxAction instead of QAjaxControlAction. 
- You mentioned this is inside of a data grid. Is the data grid the parent of $objcontrol?
- Could be a javascript error preventing this from getting set up.

Again, look at the example, and use a debugger to step through the series of javascript actions. You should see the ajax action happen in qcubed.js - postAjax.

**Comment by nlomb** [comment]
don't get it to work,

just tried the following:
(everything in simple Qform (not in Datagrid or something)
```php
         // load values from database and create QJavaScriptAutoCompleteTextBox:

         // used for Debug
         $arrDocumentfields = Documentfield::QueryArray(
            QQ::AndCondition(
               // keep this as small as possible
               QQ::IsNotNull(QQN::Documentfield()->Fieldvalue),
               QQ::NotEqual(QQN::Documentfield()->Fieldvalue, ''),
               QQ::GreaterThan(QQN::Documentfield()->Seqnr, 0)
            ),
            QQ::Clause(
               QQ::Distinct(QQN::Documentfield()->Fieldvalue),
               QQ::OrderBy(QQN::Documentfield()->Fieldvalue)
            )
         );
         foreach ($arrDocumentfields as $objDocumentfield) {
            $this->dbgAutocomplete[] = $objDocumentfield->Fieldvalue;
         }
         // $this->txtDebug = new QJavaScriptAutoCompleteTextBox($this, $this->dbgAutocomplete);
         $this->txtDebug = new QTextBox($this);
         // $this->txtDebug->AddAction(new QAutocomplete_ChangeEvent(),  new QAjaxAction($this, "txtDebug_Change"));
         $this->txtDebug->AddAction(new QChangeEvent(), new QAjaxAction('txtDebug_Change'));


      // this is the callback
      protected function txtDebug_Change($strFormId, $objControlId, $strParameter) {
         QApplication::DisplayAlert('txtDebug_Change');
      }
```
with QTextbox the Alertbox pops up, other than with QAutocompleteTextbox
you see, it's almost the same with "Textbox" and "Autocomplete Textbox",
is it possible that "autocomplete" blocks other widget events being forwarded?

BTW: tried with js from V3.0, seems to be very incompatible, won't work ...
I'm not a js - guru, so please be patient with me

PS: cannot switch this app to V.3, would take to long
PPS: If i Don't get this to work, I'll use only Autocomplete and skip the other stuff

**Comment by nlomb** [comment]
closing this, 
issue has nothing to do with QDatagrid at all
