### ISSUE TITLE
Meta controls obsolete?

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#845]
Please describe how to work without old meta controls.
I have old meta controls code and i need to rewrite it to new qcubed 3 beta.
Do you have some example?
Code generator doesn't  generate meta anymore.

**Comment by spekary** [comment]
MetaControls got renamed to ModelConnectors. See the 2nd item on page 3 of the examples "ModelConnectors". They are very similar to MetaControls, but you can now double-click on a control and select what properties you want to be in the generated version of the control.

**Comment by vmakre** [comment]
@spekary how i can get enum type values as SelectBox or Radio buttons from coegenerated modelconnector  or it is impossible?. It shows only label or text generated models. Is there any easy way?. Enum is defined as {'value1','value2',...} or there is better solution? I have a lot of enum fields please help me. Also i have some SET type of tables as i expect to get checkboxes.

**Comment by spekary** [comment]
First you have to create the correct data structures. See http://examples.qcu.be/assets/_core/php/examples/more_codegen/type_tables.php and the related association tables example for how to set that up. 

Beta 3 will let you create association tables pointing to type tables, which implements the SET functionality you want. Regular type tables will create the enums. Beta 3 examples shows how to do all this.

If you point to a type table using a foreign key, the ModelConnector will generate a QListBox. If you create an association table that points to a type table on one side using a foreign key, the ModelConnector will generate a QCheckBoxList. 

Beta3 adds the ability for plugins to inject themselves into this as an option, so potentially other widgets that implement lists or selection lists could be created to do this in the ModelConnector.
