### ISSUE TITLE
Gedit (Ubuntu Users) php.lang for QCubed

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#850]
Just made a custom "lang.php" including QCubed Keywords, see attachment,
maybe this is useful for someone...
rename and copy into "/usr/share/gtksourceview-3.0/language-specs/php.lang"
(or anything matching in your system)

[php.txt](https://github.com/qcubed/framework/files/62322/php.txt)

**Comment by kukrik** [comment]
I use itself traditional Application::Translate() or _p(), with Poedit. After easier to translate into other languages as needed...

Your suggested is a new thing for me, I find it difficult to understand:) ...

**Comment by matthiaz** [comment]
@kukrik I don't think this has anything to do with translations.

If I understand it correctly this is used for syntax highlighting in gedit

I use Netbeans myself, on KDE so I can't test this. But it might be interresting to some. 
@nlomb  I think it might be better to add this to the wiki. This is not an "issue" that needs to be solved. It's more like a "you can use this if you want", right?

**Comment by kukrik** [comment]
Oki-toki :)! I got it all wrong. I did not look at the title properly. @nlomb could further describe the purpose, and the purpose of the guide, etc....
But new ideas are always welcome...

**Comment by kukrik** [comment]
Here specified in the question of whether all meant Gedit: https://wiki.gnome.org/Apps/Gedit?

**Comment by nlomb** [comment]
Sorry, didn't want to confuse anyqone ...
yes, it's used for syntax highlighting in gedit
will try to put it into wiki soon

**Comment by nlomb** [comment]
ok, closing this
looking for a place in wiki

**Comment by kukrik** [comment]
This wiki is just a halter https://github.com/qcubed/framework/wiki. When you are ready to edit, then you need to ask @spekary to put etc ...

It would be a good opportunity for us, who would also be interested.
