### ISSUE TITLE
The Save, Regenerate and Reload button only saves

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#864]
After the button is pressed, `codegen_options.json` is written, but regeneration and reload does not.

**Comment by vaibhav-kaushal** [comment]
How do I reproduce this issue?

**Comment by spekary** [comment]
1) Add define ('__DESIGN_MODE__', true); to configuration.inc.php
2) Code generate
3) Go to the Form Drafts
4) Go to any edit page
5) Right click on a control
6) Change something, then click the button at the bottom (Save, Regenerate and Reload)

This worked at one point, then stopped working. Haven't had time to look into it.

**Comment by spekary** [comment]
Fixed by #1017
