### ISSUE TITLE
Example Soap Service Appears Broken

### ISSUE THREAD

**Issue by spekary** [qcubed/framework#876]
Soap service example appears broken in 3.0.

**Comment by olegabr** [comment]
http://localhost/example.com/vendor/qcubed/framework/assets/php/examples/communication/soap.php

It works for me:

![2016-01-09 17 09 11](https://cloud.githubusercontent.com/assets/2850808/12215746/5cf61676-b6eb-11e5-8844-953ba4941a8c.png)

**Comment by kukrik** [comment]
@olegabr cited links work  also for me.  Only this example  http://localhost/example.com/vendor/qcubed/framework/assets/php/examples/communication/soap.php does not work.

**Comment by olegabr** [comment]
@kukrik, this screenshot is taket from the `communication/soap.php` example on my local machine. It means that it works for me. Your problem with it is somewhere around paths, I believe.

There is your original message:

> @spekary, here is one more mistake ...
I do not know if this is only a problem for me. But the example http://localhost/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php does not work correctly, the address is not correct, one has a double slash http:// next. I put the error message here:

```
Notice: Undefined index: HTTP_HOST in /Users/.../.../WEB/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php on line 48

Call Stack:
    0.0004     233936   1. {main}() /Users/.../.../WEB/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php:0


Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http:///qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/example_service.php?wsdl' : failed to load external entity "http:///qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/example_service.php?wsdl"
 in /Users/.../.../WEB/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php:54
Stack trace:
#0 /Users/.../.../WEB/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php(54): SoapClient->SoapClient('http:///qcubed-...')
#1 {main}
  thrown in /.../.../WEB/qcubed-shannon/vendor/qcubed/framework/assets/php/examples/communication/soap.php on line 54

Process finished with exit code 255
```

> EDIT: For more information as far as the upgraded version of PHP 5.6.16 apart. Before that, I had a version 5.5.27, this example worked for me. Whether it was one of the reasons?

You don't have the HTTP_HOST field in the `$_SERVER` PHP variable. Docs says that:
> 'HTTP_HOST' Contents of the Host: header from the current request, if there is one.

Why you don't have it?

**Comment by kukrik** [comment]
I'll take a little time off and explore more ... I will let you know...

**Comment by kukrik** [comment]
I do not know how to give a logical explanation, this problem is probably a bug in PHP 5.6.

Tried and was testing PHP versions 5.5 and 7.0. My problem described has disappeared, and works as expected.

Specifically - what PHP versions was testing for soap:

- PHP 5.5.31 and PHP 7.0.2 at this example is running
- PHP 5.6.17 at this example does not work

**Comment by kukrik** [comment]
The problem is solved. A very simple explanation - must to uncomment "always_populate_raw_post_data = -1" in php.ini.

Topic may close.
