### ISSUE TITLE
composer update issues

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#878]
When I do `composer update` I have a message `Copying files from /home/olegabr/work/example.com/vendor/qcubed/framework/install/project to /var/www/example.com/project`. Does it preserve my changes I've made in files in the `/var/www/example.com/project` folder?

Second issue is the warning message:
```
Warning: Ambiguous class resolution, "SimpleReflection" was found in both "/home/olegabr/work/example.com/vendor/lastcraft/simpletest/reflection_php4.php" and "/home/olegabr/work/example.com/vendor/lastcraft/simpletest/reflection_php5.php", the first will be used.
```
It can frustrate new qcubed users.

## The full update listing:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                        
  - Installing qcubed/framework (dev-beta-3.0 c02833e)
    Cloning c02833e3ce567b1e0e4af5c354d16c28d0f2841b

Copying files from /home/olegabr/work/example.com/vendor/qcubed/framework/install/project to /var/www/example.com/project
Generating autoload files
Warning: Ambiguous class resolution, "SimpleReflection" was found in both "/home/olegabr/work/example.com/vendor/lastcraft/simpletest/reflection_php4.php" and "/home/olegabr/work/example.com/vendor/lastcraft/simpletest/reflection_php5.php", the first will be used.
```

**Comment by spekary** [comment]
Yes, it is supposed to only do the copy if the file does not exist. Perhaps we should hide that message if there are no files to copy.

And yes, the other problem is a pain. Not sure what to do, other than remove dependencies on simple test, which means rewriting the unit tests to depend on some other library. Or, perhaps propose a fix at the simpletest site. It looks like very little work is being done there. There is an open push request that has been sitting for 4 months. I posted an issue on their website, but not hopeful anyone will respond. Perhaps its time to move to a different test platform.

**Comment by vaibhav-kaushal** [comment]
Codeception works fine. We are using it. The pain there is - PHP 7 support is not yet planned. I think we could look into that.
