### ISSUE TITLE
Cache and uploads folders in assets needs to be rethinked

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#889]
Moved from #870 

As @kukrik mentioned already, we need two cache folders: one for php-accessible things, and it should be full filesystem path with `__DOCROOT__`, and another one for web-accesible goods, and it should be relative to site domen, e.g. for `http://example.com/project/assets/cache/myphoto.png` it should be `/project/assets/cache`

For the first one we have `__TMP__`. For the second we don't have one place, but only images cache in the `__APP_IMAGE_CACHE__` define. We should have `__APP_CACHE_ASSETS__ `instead and, may be, `__APP_IMAGE_CACHE_ASSETS__` defined as `__APP_CACHE_ASSETS__  . '/images'`. And we need to have `__APP_CACHE__` as a full-path version of the  `__APP_CACHE_ASSETS__` with a `__DOCROOT__` included. The `__APP_IMAGE_CACHE__` becomes a full-path version of the `__APP_IMAGE_CACHE_ASSETS__` define.

Uploads are different. All other caches are volatile and can be cleared in any time. Uploads are not. They are a part of user expirience and should be preserved. That is a reason to maintain it separately from cache directory. It means that the current `__APP_UPLOAD__` is done right. But it lacks it's `ASSETS` counterpart: `__APP_UPLOAD_ASSETS__` that is needed to be used by client code to form URI-s of uploaded items. The original `__APP_UPLOAD__` is used by the code that needs to work with file in a filesystem.

**Comment by olegabr** [comment]
There are three `configuration.inc.php` files now:
 - `includes/configuration/configuration.inc.php`
 - `install/project/includes/configuration/configuration.inc.sample.php`
 - `travis/configuration.inc.php`

And all three are very different. Especially the `install/project/includes/configuration/configuration.inc.sample.php` one.

@spekary, can you please explain when first and second files are used?

**Comment by spekary** [comment]
> includes/configuration/configuration.inc.php

Do you mean project/includes/configuration/configuration.inc.php? That would be the currently active configuration file for the project.

install/project/includes/configuration/configuration.inc.sample.php is the sample file that gets installed into project/includes/configuration. We need some place to store the sample configuration file, and we are constantly adding to it. However, the active configuration.inc.php is not something we want to change. So, this is currently our best way to make changes that require a configuration entry without actually editing someone's active configuraiton.

travis/configuration.inc.php is the configuration for the travis build. It needs to work for the travis environment. Again, we need that to be somewhere. Perhaps we should make the travis build a separate repository, like the composer repo is? It doesn't really bother me that it is where it is, and it makes it a little easier to debug problems with the travis build by leaving it where it is.

**Comment by olegabr** [comment]
> Do you mean project/includes/configuration/configuration.inc.php? That would be the currently active configuration file for the project.

No, I have a fresh git cloned qcubed repo with no project installed. it has a file `includes/configuration/configuration.inc.php` which looks outdated now, and the file `install/project/includes/configuration/configuration.inc.sample.php` which looks actively used in 3.0

What we should do with the old one? Should we remove it completely?

**Comment by spekary** [comment]
That configuration directory is on the main branch, but is not in the beta-3 branch.

**Comment by olegabr** [comment]
Ok, there just two config files that needs to be modified in this issue:
 - `install/project/includes/configuration/configuration.inc.sample.php`
 - `travis/configuration.inc.php`
