### ISSUE TITLE
MySqli Error: Not unique table/alias: 't0'

### ISSUE THREAD

**Issue by koopa** [qcubed/framework#891]
I got this error in the beta-3.0 branch when doing joins in conditions.

Adding the following two lines in the constructor of QPartialQueryBuilder seems to fix it. 

	$this->intTableAliasCount = &$objBuilder->intTableAliasCount;
	$this->intColumnAliasCount = &$objBuilder->intColumnAliasCount;

**Comment by spekary** [comment]
Can you create a unit test that points out the problem? I am surprised that isn't caught by the current unit tests.

**Comment by koopa** [comment]
Can you try if this causes an error
```
        $objPersonArray = Person::QueryArray(
            QQ::All(),
            QQ::OrderBy(
                QQ::IsNotNull(QQN::Person()->ProjectAsManager->Description)
            )
        );
```

**Comment by spekary** [comment]
Great catch and fix. I submitted your unit test and your fix, which appears to work well.
