### ISSUE TITLE
QDataGrid2 connects to  external site

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#896]
just found out that QDataGrid2 connects to an external site, see code
file: QDataGrid2Base.class.php
```php
...
	public function __construct($objParentObject, $strControlId = null)	{
		try {
			parent::__construct($objParentObject, $strControlId);

			$this->AddCssFile('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');

			$this->AddActions();

		} catch (QCallerException  $objExc) {
			$objExc->IncrementOffset();
			throw $objExc;
		}
	}
...
```
I think it should be possible to deactivate this, in a closed environment or with no internet connection this may produce errors or strange behaviour.

**Comment by spekary** [comment]
Good point. We should download this then and include it in our distribution. FontAwesome is MIT license, so shouldn't be a problem.
