### ISSUE TITLE
Navigation in QDatagrid2

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#901]
I think navigation in a Datagrid should be possible also with the keyboard,
eg. PageDown and PageUp for the Paginator and
ArrowDown / Up to move in  the rows.

Any idea how I can achieve this ?

**Comment by matthiaz** [comment]
You can probably make a plugin for this
Jquery has several plugins that allow shortcuts to be assigned. 
http://www.stepanreznikov.com/js-shortcuts/

That said. My personal opinion is to limit the amount of shortcuts you overwrite. For example:
PageUp and PageDown already do something in the webbrowser: they scroll up and down. 
If you change that functionality to something else, people will be surprised and maybe even annoyed. So try to use shortcuts that are not used by the browser and the operating system. 

Regards
Matthias

**Comment by nlomb** [comment]
OK, with PageUp and PageDown You are right, should use other shortcuts

I think in the QPaginator class I can easyly add a QKeyboardEvent that increments or decrements "$this->objPaginatedControl->PageNumber".

But how can I access the Rows ?
Maybe I have to add a QButton instead of the default label and set focus this ?

**Comment by matthiaz** [comment]
I would change as little as possible to the PHP code.

Try making a jquery plugin that triggers that actual mouse clicks.

**Comment by nlomb** [comment]
thanks,
will try later ...
have to get used to the new controls, events and actions in V3.0
