### ISSUE TITLE
QCubed V 3.0 possible bug with Google Chrome Browser

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#903]
just tested QCubed V 3.0 examples with Google Chrome Version 48.0.2564.97 m / Win 7 in VirtualBox

see attached screenshot ...
![screenshot-01](https://cloud.githubusercontent.com/assets/3634541/12775700/47b95da4-ca50-11e5-88be-8bdc1fd675ca.png)

Entering something in the search box does always reload the complete form with all the panels and the filter in list panel is not applied.

works well with Firefox,Safari and Internet Explorer on the same VirtualBox,
Client is Win 7 with all updates applied, Server is Ubuntu 14.04 LTS with all updates applied

**Comment by kukrik** [comment]
I see it is only now that the search box is case-sensitive. Not only in Chrome, also in Firefox ja Safari... Perhaps this is one reason, or not?

**Comment by nlomb** [comment]
just tried out:
the search box in my installation (from latest release by composer) is not case sensitive,
also: clicking on a row in the listpanel in FF opens the edit dialog, clicking row in Chrome the listform
is reloaded, entered chars in searchbox are gone and the listform is reloaded.

so I believe it has to to with event handling / bubbling in Chrome

if You want to try out i can give You access to my demo installation via https

**Comment by nlomb** [comment]
just found out there also seems to be another problem,
I will open a new issue for this:

**Comment by spekary** [comment]
Should have nothing to do with browser. The search is using 'LIKE'  in sql to find things. If the sql engine is case sensitive, then the search will be case sensitive.

**Comment by nlomb** [comment]
Ii think we misunderstand here:
the problem has nothing to do with cases.
The problem is:
with FF, Safari or IE: if I enter something into the searchbox,
the listpanel redraws and shows only matching entries, the searchbox stays unchanged.
with Chrome (Win7): if I enter something into the searchbox,
the complete form is redrawn, the searchbox is empty and the listpanel shows all entries.
So strongly believe it has something to do with how Chrome Browser handles the triggered events.

see screenshots (taken after entering an "y" into the searchbox,
safari.png shows what it should look like, chrome.png shows what happens:
safari.png:
![safari](https://cloud.githubusercontent.com/assets/3634541/12809301/3e1cc334-cb1e-11e5-8ef4-669418f72ea5.png)
chrome.png:
![chrome](https://cloud.githubusercontent.com/assets/3634541/12809306/4718c6ae-cb1e-11e5-952b-34706dbe0c64.png)

update: just tested the same with chrome Ubuntu 14.04 LTS, here its works as it should, see:
![chrome-ubuntu](https://cloud.githubusercontent.com/assets/3634541/12809430/4358428c-cb1f-11e5-8790-024abff66a2c.png)

so the problem occurs with chrome on win7 in virtualbox, cannot test further,
will recommend FF or Safari for my windows users

**Comment by nlomb** [comment]
definitely NOT a bug in QCubed; will recommend FF or Safari for my windows users 
closing

**Comment by spekary** [comment]
I would like to leave this open for now. A goal of QCubed is to be platform agnostic. This includes browsers, sql servers, web servers. Using jQuery is supposed to help with that on the browser side, but if something is behaving badly, we should see why. Chrome has really good javascript debugging tools, so we should be able to see what is happening. It could be a fixable error in our javascript.

**Comment by nlomb** [comment]
@spekary 
Agreed, If You need more information about my testcase just contact me,
I can give You also access to the server where the screenshots are from ...

**Comment by vaibhav-kaushal** [comment]
Is it still happening? I have no Windows 7 system around me to test (nor an ISO). Also, have you tried resetting the cache? Which SQL server (MySQL/PostgreSQL) were you using in the virtualbox system?

**Comment by nlomb** [comment]
just tested again ...
behaviour has changed with latest qcubed version 
just updated to qcubed version "dev-beta-3.0 20c100e" via composer ad did a complete new codegen
now the (automatic) search does not work at all, entering something in the searchbox has no effect.
see screenshots firefox.png and chrome-2.png
![firefox](https://cloud.githubusercontent.com/assets/3634541/16198454/48988fd8-3706-11e6-9466-b4a7dde57b6b.png)
![chrome-2](https://cloud.githubusercontent.com/assets/3634541/16198459/4fa79396-3706-11e6-9060-56b364a19809.png)

**Comment by kukrik** [comment]
Basically, a similar problem is described, may be merge into one of the problems: https://github.com/qcubed/framework/issues/996?

**Comment by spekary** [comment]
I can't reproduce this. I don't think this is a server problem. Its either javascript or ajax issue. Can you open your browser's javascript debugger and see if there are any errors? What is your client platform, Windows?

**Comment by nlomb** [comment]
found out something:

works in Ubuntu with Firefox and Chromium,
works in Win7 with IExplorer, Firefox, Safari, but not with Chrome...
started dev-tools in Chrome / Windows, got:
"qcubed.js:496 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."
```js
/////////////////////////////
// QForm-related functionality
/////////////////////////////

this.wrappers = [];

if ('localStorage' in window && window['localStorage'] !== null) {
   $j(window).on ("storage", function (o) {
       if (o.originalEvent.key == "qcubed.broadcast") {
           qcubed.updateForm();
       }
   });
}
```
don't get similar messages in other browsers
client is "Windows 7 Home Premium SP 1 32Bit" in Oracle Virtual Box under Ubuntu 14.04.1 with Gnome Desktop

**Comment by matthiaz** [comment]
@nlomb 
Have you tried: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by nlomb** [comment]
@matthiaz 
just tried, no change (restarted browser)

**Comment by spekary** [comment]
What about the "allow local data to be set" option in Chrome. 

I have not found a good way to detect this setting. The use of localdata in qcubed.js is part of the data Watcher functionality, and is used to notify other browser windows when data has changed. Its not critical. It would be great if we could detect that Chrome is not allowing access, but I don't see any way of doing that currently.

**Comment by spekary** [comment]
Try going in to your qcubed.js file and commenting out the offending line like and matching brace like this and rerunning it. We might not need the check, since we are just adding an event handler. 

```
// if ('localStorage' in window && window['localStorage'] !== null) {
   $j(window).on ("storage", function (o) {
       if (o.originalEvent.key == "qcubed.broadcast") {
           qcubed.updateForm();
       }
   });
// }

**Comment by nlomb** [comment]
@spekary 
just did so, error message gone but still not working, sorry

**Comment by spekary** [comment]
Not working, but no javascript error messages at all?

**Comment by spekary** [comment]
I did some checking, and sort of recreated the problem. Not sure. It produced some useful fixes that I submitted in #1006. However, according to my tests, the problem is that you have turned off cookies. Do you see a round icon with a red x in the upper right corner next to the URL box? If so, clicking that should tell you that you have cookies turned off, and direct you how to turn them on. 

Another symptom of this problem is that no ajax is working at all. So, not only can you not type, you cannot click on a row. The problem is that without cookies, it cannot recover the session, and so might not be able to get the formstate. Depends how you have your formstate storage configured.

I tested with Win 7 and latest Chrome, and could only recreate the problem by turning off cookies. With cookies turned on, it worked fine.

**Comment by nlomb** [comment]
yes, it was the cookie - setting:
I always block all cookies for security / tracking reasons
now added exception for my server/port, works OK

must have overlooked this setting in Win/Chrome because I only use Win for checking Layout with other browsers, especially IE

sorry for the inconvenience, thanks a lot

**Comment by nlomb** [comment]
think I should close this,
not a QCubed bug but a client misconfiguration
