### ISSUE TITLE
QCubed V 3.0 with https

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#904]
just made https accessible QGubed Demo / Examples site, found the following problem:

with ordinary http clicking on a QDatagrid field the edit - dialog opens,
connecing the same site over https (only another apache virual host) clicking  the same field
does not do anything

screenshot  from issue: https://github.com/qcubed/framework/issues/903
![screenshot-01](https://cloud.githubusercontent.com/assets/3634541/12775700/47b95da4-ca50-11e5-88be-8bdc1fd675ca.png)

(testet with Win 7 and Ubuntu Client, same in Chrome and FF, did not test IE and Safari)

**Comment by nlomb** [comment]
found out,
failure is caused by loading jquery from web instead from local host in "configuration.inc.php"
```
176:   define ('__JQUERY_BASE__', ' http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js');
177:   define ('__JQUERY_EFFECTS__', ' http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js');
```
setting this to local files fixes this

maybe someone else was trapped on this ?

**Comment by koopa** [comment]
As already mentioned in another issue those should probably be installed locally and referenced via a local path. Alternatively instead of http:// you could just use // and the appropriate protocol should be chosen automatically.

**Comment by nlomb** [comment]
it's already installed locally by default, 
only in default "configuration.inc.php" local path is commented out, 
so that's not a bug, only local misconfiguration ...
just kept this open as a hint for other users

**Comment by spekary** [comment]
I think the problem here is that if you connect over https, you cannot then refer to outside assets using http. If you change it to https in the configuration file, it should work. Of course, referring to it locally should work too. This was an issue with v2 as well, and all frameworks for that matter.

**Comment by nlomb** [comment]
thanks to all,
as i said, it's already solved, see here: https://github.com/qcubed/framework/issues/904#issuecomment-179292395
closing this now
