### ISSUE TITLE
QProgressBar

### ISSUE THREAD

**Issue by neuroticimbecile** [qcubed/framework#905]
Hi All,

Please point me to a working example of QProgressBar for qcubed v2.2.3

I found it in 
=====
```
./includes/qcubed/controls/QProgressbar.class.php
./includes/qcubed/_core/base_controls/QProgressbarGen.class.php
./includes/qcubed/_core/base_controls/QProgressbarBase.class.php
```
=====

But it doesn't seem to work when used like this:
=====
```
protected function Form_Create() {
    $this->objQProgressBar = new QProgressBar($this);

    $this->btnStart = new QButton($this);
    $this->btnStart->Text = QApplication::Translate('Start');
    $this->btnStart->AddAction(new QClickEvent(), new QAjaxAction('btnStart_Click'));
}

protected function btnStart_Click($strFormId, $strControlId, $strParameter) {
    for ($i = 0; $i < 100; $i++) {
       $this->objQProgressBar->Value1($i);
       sleep(1);
    }
}
```
=====

It just displays the progress bar at 0% and then suddenly at 100% after some seconds.

Thanks,
-eric

**Comment by spekary** [comment]
Correct. This would be true of all the controls, and any client-server arrangement. You are not giving any opportunity for the server to speak to the client. 

Understand that the server must send information to the browser for the browser to do anything. That happens after all of your code is done running. This is one of the difficulties of web programming.

To do what you are trying to do, there are a couple of ways:
1. Create a javascript function that will periodically update your progress bar widget using the JQuery UI api.Have your button do a QJavascriptAction that calls your function.
2. Use QJsTimer to give yourself timer events from the browser, and attach an action to it that updates the progress bar.

For a demo of whether the progress bar is working, change your code to something like this:
```
protected function btnStart_Click($strFormId, $strControlId, $strParameter) {
    $intVal = $this->objQProgressBar->Value;
    if ($intVal < 100) {
        $this->objQProgressbar->Value = $intVal + 5;
    }
}
```

Every time you press the button, you should see the progress bar grow.

**Comment by spekary** [comment]
If you want something that truly creates a live link between the browser and client, the you need something like WebSocket. Its pretty advanced stuff. There are some PHP libraries out there to do this. It involves setting up a special daemon on your server that listens to a WebSocket port, and responding to web socket requests. There is also a custom javascript part needed on the server side. Something to look into some day.

**Comment by neuroticimbecile** [comment]
Hi Shannon,

Thank you very much for the explanation and the pointers.
And thank you more for keeping qcubed alive.

Regards,
-eric
