### ISSUE TITLE
One database different models or generated tables with different prefixes

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#908]
This is my idea for feature request , not much complicated but need to be good rethinked .
My idea is we can define db prefixes per db connection , if db prefix is defined only tables with this prefix
will be used in codegen and grouped for this dbconnection(sometime we need to use some tables not all). In folder generated  we can use prefix-ed subfolder (this is idea but not mandatory). Calling DBModels will be DBPrefix_Table->   or something similar , but there must be an option for calling models with prefix or without prefix. In multilanguage site will be good  dbmodel to be same for all languages but need to go to different tables (multilanguage in database) . This is good for multilanguage and multisite implementations  . Also old implementation stays unchanged , or at first to define new db connection with prefix as different from original one(db connection for prefixed tables).

**Comment by matthiaz** [comment]
I think you can already do this in codegen_settings.xml
see qcubed/includes/configuration/codegen_settings.xml

**Comment by vmakre** [comment]
Yes i will check codegen_settings.xml  i forgot there where options for manipulating
with prefix and suffix-es . Thanks @matthiaz  , we can close  this issue .
