### ISSUE TITLE
Codegen MaxLength for decimal (MySQL)

### ISSUE THREAD

**Issue by koopa** [qcubed/framework#921]
Not sure if this only affects MySQL or not.

I encountered a problem where the Connector Codegen for a decimal field generated a wrong value for the MaxLength constant.

        const <?= $objColumn->PropertyName ?>MaxLength = <?= $objColumn->Length ?>;

Now if you use for example `DECIMAL(3,1)` and try to save the value "12.3" then it complains about MaxLength, which in this case is 3 (from objColumn->Length).

I don't know enough about the internals of the codegen table field reflection used by the MySQL adapter, but my guess would be it should be fixed somewhere there, and add +1 to `$objColumn->Length` if it turns out to be a decimal field.

**Comment by spekary** [comment]
This is not MySQL specific. But, I think you are right in that 1 should be added. MaxLength is specifically for use by the text field validator, and so 3 is the wrong value when a decimal point is expected.
