### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#935]
Hello,

I have en encoding problem with Character Encoding (All is set to UTF-8)

I set up the QCubed Demo and entered a new person to the database, see 
![utf-8](https://cloud.githubusercontent.com/assets/3634541/13879195/73d96670-ed16-11e5-9cc8-84f22250864f.png)

looking into database i get:
```
mysql> select * from person;
+----+--------------------------------+--------------------------------+
| id | first_name                     | last_name                      |
+----+--------------------------------+--------------------------------+
|  1 | John                           | Doe                            |
|  2 | Kendall                        | Public                         |
|  3 | Ben                            | Robinson                       |
|  4 | Mike                           | Ho                             |
|  5 | Alex                           | Smith                          |
|  6 | Wendy                          | Smith                          |
|  7 | Karen                          | Wolfe                          |
|  8 | Samantha                       | Jones                          |
|  9 | Linda                          | Brady                          |
| 10 | Jennifer                       | Smith                          |
| 11 | Brett                          | Carlisle                       |
| 12 | Jacob                          | Pratt                          |
| 13 | Ã¤Ã¶Ã¼Ã„Ã–ÃœÃŸ                 | Ã¤Ã¶Ã¼Ã„Ã–ÃœÃŸ                 |
+----+--------------------------------+--------------------------------+
13 rows in set (0.00 sec)
```
then do: 
```
mysql> update person set first_name = 'äöüÄÖÜß' where id = 13;
Query OK, 1 row affected (0.50 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from person;
+----+----------------+--------------------------------+
| id | first_name     | last_name                      |
+----+----------------+--------------------------------+
|  1 | John           | Doe                            |
|  2 | Kendall        | Public                         |
|  3 | Ben            | Robinson                       |
|  4 | Mike           | Ho                             |
|  5 | Alex           | Smith                          |
|  6 | Wendy          | Smith                          |
|  7 | Karen          | Wolfe                          |
|  8 | Samantha       | Jones                          |
|  9 | Linda          | Brady                          |
| 10 | Jennifer       | Smith                          |
| 11 | Brett          | Carlisle                       |
| 12 | Jacob          | Pratt                          |
| 13 | äöüÄÖÜß        | Ã¤Ã¶Ã¼Ã„Ã–ÃœÃŸ                 |
+----+----------------+--------------------------------+
13 rows in set (0.00 sec)
```
ii get this:
![utf-8-2](https://cloud.githubusercontent.com/assets/3634541/13879314/1cd3b7e4-ed17-11e5-94fa-2105cd7019b1.png)

"mysqldumping" the person - table and "file -i person.sql" gives 
```
user@server-02:~$ mysqldump -u root -pN0r6erT qcubed_demo person > person.sql
user@server-02:~$ file -i person.sql
person.sql: text/plain; charset=utf-8
user@server-02:~$ 
```
environment is also UTF-8
```
user@server-02:~$ env | grep -i lang
LANG=de_DE.UTF-8
```
has anyone an idea where to look further

thanks a lot

**Comment by nlomb** [comment]
solved:
export per mysqldump, iconv from CP1252 to UTF-8, reimport, everything works fine
source data was in CP1252 instead of UTF-8 despite "file -i" said "UTF-8"
(have to keep this in mind ...)

**Comment by kukrik** [comment]
I had the same problem.
Umlauts are similar to the German and Estonian. This problem is not English.

I solved this problem like this, please see the screenshots:

<img width="1263" alt="screen shot 2016-03-19 at 19 08 38" src="https://cloud.githubusercontent.com/assets/2853034/13900156/2d498134-ee08-11e5-867d-cbb600ac27bd.png">

<img width="1280" alt="screen shot 2016-03-19 at 19 09 06" src="https://cloud.githubusercontent.com/assets/2853034/13900113/3a35f72a-ee07-11e5-9574-526b271ab1ae.png">
<img width="1280" alt="screen shot 2016-03-19 at 19 08 00" src="https://cloud.githubusercontent.com/assets/2853034/13900112/3a35400a-ee07-11e5-9174-3eacce901e48.png">

**Comment by nlomb** [comment]
thanks, will try this
found out that my "solution" was working, but not correct,
so dismiss this

**Comment by nlomb** [comment]
closing, see:
https://github.com/qcubed/framework/issues/936
