### ISSUE TITLE
QDadagrid2 Paginator (possible bug ?)

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#944]
Paginator "next-Item link" is not shown on first page, see:
![paginator-1](https://cloud.githubusercontent.com/assets/3634541/13945831/ae941588-f010-11e5-9ab9-9bd3aa6cd24d.png)
paginator gets displayed if You select last page and then go back, see:
![paginator-2](https://cloud.githubusercontent.com/assets/3634541/13945871/04f15990-f011-11e5-8fc8-40241ce5e9a2.png)

Screenshots are from newly update via composer and then codegen / View Form Drafts

**Comment by spekary** [comment]
Fixed in #949

**Comment by spekary** [comment]
Can you test and close this?

**Comment by nlomb** [comment]
tested with lated version
working
closing
