### ISSUE TITLE
QCubed how to save QDateTime as NULL

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#959]
@Nebster

my QCubed PHP class "Project" has a property called "Finished" which is object of QDateTime and data type "datetime" in MySQL database. I need to save NULL into database when user leaves this field blank in HTML

<input type="datetime-local" name="Finished" />

but I cannot find a way for it since PHP always throws Internal Server Error 500

if ($_GET["Finished"] != "") $objProject->Finished = new QDateTime($_GET["Finished"]);

else $objProject->Finished = ???

Will be glad for any help.

http://stackoverflow.com/questions/36696219/qcubed-how-to-save-qdatetime-as-null

**Comment by nlomb** [comment]
maybe it's a database / mysql issue,
is "null" allowed in the database column ?

just tested with V3.0 drafts 
eg: added datetime column to existig table, 
codegen and edited with created drafts, works OK
(setting datetime and also setting back to null ...)

**Comment by spekary** [comment]
This is a stackoverflow question, and he answered it himself. Was some other problem.
