### ISSUE TITLE
Error Messag "assert(): Assertion failed"

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#960]
Sometimes I'm getting this message;
```
assert(): Assertion failed

Error Type: E_WARNING

Source File: /usr/data/share/www/resources/project/generated/connector_base/ContactConnectorGen.class.php Line: 652

Line 647:    		 * Refresh this ModelConnector with Data from the local Contact object.
Line 648:    		 * @param boolean $blnReload reload Contact from the database
Line 649:    		 * @return void
Line 650:    		 */
Line 651:    		public function Refresh($blnReload = false) {
Line 652:    			assert($this->objContact); // Notify in development version
Line 653:    			if (!($this->objContact)) return; // Quietly fail in production
Line 654:    
Line 655:    			if ($blnReload) {
Line 656:    				$this->objContact->Reload();
Line 657:    			}
```
could not yet find out what it means and cannot reproduce it,
but happens sometimes at closing the Contact Edit Form (a tweaked generated Metacontrol) with or without saving..

**Comment by spekary** [comment]
It means something is calling Refresh on a ModelConnector that has not been loaded previously. Could be a newly created connector that was never actually initialized. This would generally be a bad thing, although we could always change it to do nothing if there is no object loaded.

**Comment by spekary** [comment]
Is this still a problem? Did you figure this out?

**Comment by nlomb** [comment]
@spekary 
still a problem, seemed to have disappeared but is back now in another form
now I'm able to reproduce it, it occurs if I do a redirect to the same form with loading the same data again.

Can anyone explain what this "assert" does so that I can circle this in ?

**Comment by spekary** [comment]
Refresh is supposed to take the information in the model object and put it into the controls in the connector, which are what is shown on the form. The assert is there to make sure there is a model object. The model object must be loaded before a Refresh. The assert means you are doing things out of order...you are trying to load the controls in the form before you have queried the database for the data to put in the controls, or in the case of doing a "new", you have not created an empty object to edit yet.

**Comment by nlomb** [comment]
thanks, solved
was a bug redirecting back to previous QForm
```php
protected function btnCancel_Click($strFormId, $strControlId, $strParameter) {
	QApplication::Redirect($this->strReturl . '?intId=' . $this->intRefId);
}
```
"$this->strReturl" did not point to the expexted QForm.
I think we can close this
