### ISSUE TITLE
QPanel template broken

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/framework#981]
I'm fairly certain this is a bug and I have no idea how to fix it.

I have a plain QForm with one QPanel and one QTextBox. The parent of the QTextBox is the QPanel.
If I have AutoRenderChildren = true and no template defined, the text box displays perfectly.
However, if I define a template for the QPanel I get: Undefined GET property or variable in 'QPanel' class: txtTest

My code is below for each element.

test.php
```
require_once(dirname(__FILE__).'/../qcubed.inc.php');

class TestForm extends QForm {
    protected $pnlTest;
    protected $txtTest;
    
    protected function Form_Create() {
        parent::Form_Create();
        
        $this->pnlTest = new QPanel($this);
        $this->pnlTest->AutoRenderChildren = false;
        $this->pnlTest->Template = __PAGE_TEMPLATES__ . '/panels/test_pnl.tpl.php';
        
        $this->txtTest = new QTextBox($this->pnlTest);
        $this->txtTest->Name = 'Test';
        $this->txtTest->Text = 'Stuff';
        
    }
}
TestForm::Run('TestForm', __PAGE_TEMPLATES__ . '/test.tpl.php');
```
test.tpl.php
```
require_once(__CONFIGURATION__ . '/header.inc.php');
$this->RenderBegin();
$this->pnlTest->Render();
$this->RenderEnd();
require_once(__CONFIGURATION__ . '/footer.inc.php');
```
test_pnl.tpl.php
`$this->txtTest->Render();`

Error Message
 ```
Exception in PHP Script /project/webroot/test.php
Undefined GET property or variable in 'QPanel' class: txtTest

Exception Type: QUndefinedPropertyException

Source File: C:\wamp2_5\www\AA4_Qcubed_2016\site\aa4\vendor\qcubed\framework\includes\base_controls\QControlBase.class.php Line: 406

Line 401:    					ob_clean();
Line 402:    				}
Line 403:    
Line 404:    				// Evaluate the new template
Line 405:    				ob_start('__QForm_EvaluateTemplate_ObHandler');
Line 406:    				require($strTemplate);
Line 407:    				$strTemplateEvaluated = ob_get_contents();
Line 408:    				ob_end_clean();
Line 409:    
Line 410:    				// Restore the output buffer and return evaluated template
Line 411:    				if ($strAlreadyRendered) {

```

**Comment by spekary** [comment]
txtTest is a member of the form TestForm. That is where you defined it and that is where PHP puts it. In your template, "$this" is the control that the template is attached to. So when you say $this->txtTest, you are asking for a member of pnlTest. txtTest is not a member of pnlTest.

When you defined txtTest, and set its parent as pnlTest, that does not make it an actual member of that object. The whole parent-child thing is a QCubed construct, and is primarily an aid to making sure that things that are visually contained within an object in the html get drawn in the right order.

A couple of ways to fix this:
- make txtTest public and refer to it in the template with $this->Form->txtTest
- Give txtTest an id, and refer to it as $this->Form->GetControl(id)
- Give txtTest an id, and refer to it as $this->GetChildControl(id)
- Subclass QPanel, make txtTest a member of that subclass, and then you can use $this->txtTest in the template for the panel.

One thing you should do is set up a debugging environment so you can easily set breakpoints and see the members of the different objects. There are a many different IDEs, like Eclipse or PHPStorm that support XDebug. If you are developing a significant app, you really want something like that to help you understand what is happening in the architecture.
