### ISSUE TITLE
Questioning HHVM compatibility

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#984]
One of the primary reasons we wanted to move to HHVM for 3.0 was that it was fast. PHP 7 happens to be just as much fast and sometimes faster.

Why are we still planning for HHVM compatibility?

**Comment by spekary** [comment]
There are other reasons for HHVM compatibility. I think some tests need to be done to show how HHVM and PHP7 stack up for QCubed, especially data access, and in particular if the data access layers were made hack compatible to get it to compile into C. However, there is not much to do for basic HHVM compatibility. I have been using it for a year now, and QCubed seems to work fine with it.

**Comment by kukrik** [comment]
A small question! Is it also works well on top of the OS X platform? Or you use Linux on it?

**Comment by spekary** [comment]
Just Linux at this point, but they have released a MacOS version.

**Comment by spekary** [comment]
HHVM generally is working fine. There is a problem with using "assert", using a string in the assert, and including $this in the string. I haven't found any other problems. 

HHVM has announced that it will eventually be at feature parity with PHP7. Also, it is continuing to increase in speed, and outperforms PHP7 in many tests now.

At some point, we should add PHP7 annotations, but that is for a future version. Not sure we can do that without breaking PHP 5.6 compatibility. We could do it through code generation, but much of the code generation depends on other files that would need it too.
