### ISSUE TITLE
generated Form Drafts no longer working in "qcubed/framework (dev-beta-3.0 0f8072d)"

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#993]
latest install: "qcubed/framework (dev-beta-3.0 0f8072d)" via composer
the generated Form Drafts are no longer working, path to "nav_panel.class.php" is invalid

code in "vendor/qcubed/framework/install/project/includes/app_includes/nav_panel.class.php" is:
```php
<?php

/**
 * Class NavPanel
 *
 * This is a basic starting navigation panel that appears at the top of every list form.
 * This particular panel just loads a template to navigate back to the main
 * form list. You can modify this however you want to suit your application.
 * A list of links, button bar, or a menu bar are possibilities.
 */
class NavPanel extends QPanel {

	public function __construct ($objParent, $strControlId = null) {
		parent::__construct($objParent, $strControlId);
		$this->strTemplate = '/nav_panel.tpl.php';
	}
}
```
and should be:
```php
<?php

/**
 * Class NavPanel
 *
 * This is a basic starting navigation panel that appears at the top of every list form.
 * This particular panel just loads a template to navigate back to the main
 * form list. You can modify this however you want to suit your application.
 * A list of links, button bar, or a menu bar are possibilities.
 */
class NavPanel extends QPanel {

	public function __construct ($objParent, $strControlId = null) {
		parent::__construct($objParent, $strControlId);
		$this->strTemplate = realpath(dirname(__FILE__)) . '/nav_panel.tpl.php';
	}
}```

**Comment by spekary** [comment]
The problem is the forward slash at the beginning of the template name. That is telling it to look for the panel in root. We need to remove the slash.

**Comment by spekary** [comment]
Fixed #994

**Comment by nlomb** [comment]
thanks, works, closing this

**Comment by kukrik** [comment]
Sorry, I have to open a ticket. Are you confident that it will solve the problem?

Anyway it nav_panel.tpl.php broke. Error indicates: require (nav_panel.tpl.php): failed to open stream: No such file or directory.

What is the right solution?

**Comment by spekary** [comment]
Make sure you have updated everything and try again. Include complete text of error, including line number.

**Comment by kukrik** [comment]
I have to take the words back. I upgraded from morning with terminal through the composer: sudo composer update. Many changes came, but I do not understand that about 10 files are not updated :(.

I had to manually copy and paste. It is not normal for me.

Can you give me some good advice, how to adequately upgrade the composer?
